open-wc/open-wc

- package.json
A single browser can not run tests in multiple packages at the same
time. Limiting concurrency to 1.
> fix: testing can not be run in parallel

- packages/chai-dom-equals/package.json
- packages/storybook/package.json
- packages/testing-helpers/package.json
- packages/testing/package.json
We only use lit-html in the lit fixture. If people use lit fixture, they must already have lit-html installed so we can get away with this trick.
> chore: don't depend on lit-html directly for usage from bower

- packages/testing-helpers/README.md
- packages/testing-helpers/helpers.js
Removes flush from the docs at https://open-wc.org/recommendations/testing-helpers.html#timings
> fix: remove deprecated flush

- CONTRIBUTING.md
- packages/generator-open-wc/README.md
Fixed a typo in the contributing.md and a grammar issue in the generator-open-wc section.
Added and categorized the generators
> Typo / Grammar fix

- packages/generator-open-wc/generators/vanilla/index.js
- packages/testing/README.md
See title. I also added a note in the testing readme about chrome browser pre-requisite.
> Vanilla generator to compose with lint instead of just lint-eslint

- packages/chai-dom-equals/README.md
- packages/chai-dom-equals/chai-dom-equals.js
- packages/chai-dom-equals/test/bdd-setup.js
- packages/testing-helpers/README.md
- packages/testing-helpers/fixture.d.ts
- packages/testing-helpers/fixture.js
- packages/testing-helpers/fixtureWrapper.d.ts
- packages/testing-helpers/fixtureWrapper.js
- packages/testing-helpers/helpers.d.ts
- packages/testing-helpers/helpers.js
- packages/testing-helpers/index.d.ts
- packages/testing-helpers/index.js
- packages/testing-helpers/litFixture.d.ts
- packages/testing-helpers/litFixture.js
- packages/testing-helpers/stringFixture.js
- packages/testing-helpers/test/bdd-setup.js
- packages/testing-helpers/test/fixture.test.js
- packages/testing-helpers/test/index.html
- packages/testing-helpers/test/index.js
- packages/testing-helpers/test/index.karma.js
- packages/testing-helpers/test/stringLitFixture.test.js
- packages/testing/README.md
- packages/testing/demo/test/get-result.test.js
- packages/testing/register-fixture-cleanup.js
- packages/testing/test/side-effects.test.js
- `fixture` => `stringFixture`
- new `fixture` can handle strings and lit-html TemplateResults
- types and documentation update
> feat(testing-helpers): fixture can handle strings and TemplateResults

- packages/building-webpack/README.md
Added notes to avoid problems I ran into as a Polymer CLI user using webpack for the first time.
Also moved the npm scripts to the last step. When I hit this part of the instructions, I immediately tried running the scripts, which failed because the necessary HTML and JS files weren't set up yet. Moving this step to the end prevents this user error.
Changed one header to make it more descriptive.
I'd suggest also adding a note (either in Step 4 above or in Change the default entrypoints) describing what to do if you have more than one HTML/JS entrypoint. I'd have done that but for my complete ignorance (Can indexJS take an array? Or do they need to go to the method described in "Customizing the configuration"? Can you pass a config object with indexHTML/indexJS to createDefaultConfig?)
> fix(building-webpack): improve setup docu to minify user errors

- packages/testing-helpers/README.md
- packages/testing-helpers/elementUpdated.js
- packages/testing-helpers/index-no-side-effects.js
- packages/testing-helpers/index.js
- packages/testing-helpers/litFixture.js
- packages/testing-helpers/stringFixture.js
- packages/testing-helpers/test/elementUpdated.test.js
closes https://github.com/open-wc/open-wc/issues/172
> fix(testing-helpers): add `await elementUpdated(el)` supports stencil

- packages/owc-dev-server/README.md
> fix(owc-dev-server): fix CLI options table formatting in README

- packages/generator-open-wc/generators/app/index.js
- packages/generator-open-wc/generators/automating-circleci/index.js
- packages/generator-open-wc/generators/automating/index.js
- packages/generator-open-wc/generators/building-webpack/index.js
- packages/generator-open-wc/generators/building/index.js
- packages/generator-open-wc/generators/demoing-storybook/index.js
- packages/generator-open-wc/generators/demoing/index.js
- packages/generator-open-wc/generators/linting-commitlint/index.js
- packages/generator-open-wc/generators/linting-eslint/index.js
- packages/generator-open-wc/generators/linting-prettier/index.js
- packages/generator-open-wc/generators/linting/index.js
- packages/generator-open-wc/generators/scaffold-building/index.js
- packages/generator-open-wc/generators/scaffold-demoing/index.js
- packages/generator-open-wc/generators/scaffold-testing/index.js
- packages/generator-open-wc/generators/scaffold-vanilla/index.js
- packages/generator-open-wc/generators/testing-karma-bs/index.js
- packages/generator-open-wc/generators/testing-karma/index.js
- packages/generator-open-wc/generators/testing-wallaby/index.js
- packages/generator-open-wc/generators/testing/index.js
fixes https://github.com/open-wc/open-wc/issues/205
> "Yeoman will ensure the npm install command is only run once even if it is called multiple times by multiple generators."
https://yeoman.io/authoring/dependencies.html
> feat: npm install after running generators

- docs/ide/README.md
Just a proposal, maybe it isn't better at all, but that you will say.
I use this extension daily to develop Polymer's LitElements and I like it very much.
> docs(ide): replaced es6-string-html by lit-html

- packages/building-webpack/package.json
- packages/generator-open-wc/generators/scaffold-vanilla/templates/_package.json
- packages/owc-dev-server/package.json
lit-html bumped to 1.0.0
lit-element bumped to 2.0.1 (That was the version which uses 1.0.0 of lit-html)
> Bump lit versions to the 1.0 stable releases

- packages/testing-karma/README.md
fixes #226
I chose the merge strategy approach namely because I'm not sure how to plumb the depths of possible issues around @daKmoR's note that:
> iirc using only config set however breaks webpack configs as they need to be "carefully" copied with keeping function in tact and such... that's why we use webpack-merge generally
If anyone else has deeper insight on this, I'd be happy to make updates here.
> Merge Strategy Documentation

- packages/testing-helpers/README.md
Hey open-wc :). 
I was using the test-helpers and spotted this typo.
Cheers,
> chore(testing): fix typo in docs

- packages/demoing-storybook/README.md
In the overrides example, color, select and object are referenced but not imported nor cited in text.
Also add note about the custom element position in template
> docs(demoing-storybook): add knobs import

- packages/testing-karma/default-settings.js
previously we only excluded `test` files.
> fix(testing-karma): exclude spec files in node_modules

- packages/owc-dev-server/owc-dev-server.js
fixes the app-index path by using the current working directory instead of the __dirname path which locates to the module path.
> fix(owc-dev-server): use current working directory for app index

- packages/testing-helpers/elementUpdated.js
- packages/testing-helpers/package.json
- packages/testing-helpers/test/fixture.test.js
In IE11 and older versions of other browsers without native ShadowDOM this test works:
```js
it('my test', async () => {
class MyElement extends LitElement {
static get styles() {
return css`
:host .wrapper ::slotted(div) {
position: absolute;
}
`;
}
render() {
return html`
<div class="wrapper">
<slot></slot>
</div>
`;
}
}
const tag = defineCE(MyElement);
const el = await fixture(`<${tag}><div></div></${tag}>`);
const div = el.querySelector('div');
expect(window.getComputedStyle(div).position).to.equal('absolute');
});
```
AssertionError: expected 'static' to equal 'absolute'
ShadyCSS polyfill hasn't yet rewrite all class names and apply styles to elements. To ensure it did its job we can run `window.ShadyDOM.flush()`.
```js
const el = await fixture(`<${tag}><div></div></${tag}>`);
const …
```
> [testing-helpers] ensure ShadyDOM finished its job in fixture

- packages/demoing-storybook/withClassPropertiesKnobs.js
properties do not need a type field. see https://lit-element.polymer-project.org/guide/properties#conversion
> fix(demoing-storybook): allow untyped properties

- packages/building-rollup/README.md
- packages/building-rollup/demo/js/rollup.config.js
- packages/building-rollup/demo/js/rollup.modern.config.js
- packages/building-rollup/demo/js/rollup.visualizer.config.js
- packages/building-rollup/demo/ts-babel/rollup.config.js
- packages/building-rollup/demo/ts/rollup.config.js
- packages/building-rollup/modern-and-legacy-config.js
- packages/building-rollup/modern-config.js
- packages/building-rollup/plugins/rollup-plugin-modern-web/rollup-plugin-modern-web.js
- packages/building-rollup/plugins/rollup-plugin-modern-web/utils.js
Fixes https://github.com/open-wc/open-wc/issues/283
- Fixes docs to mention specifying a config file to rollup
- Fixes default config to be exported as a commonjs module, instead of an es module
> fix(building-rollup): default configs should be commonjs modules

- karma.conf.js
- karma.es5.bs.config.js
- karma.es5.config.js
- package.json
This reduces the time the ci needs to run the tests by ~50%.
e.g. ~2:30min instead of ~5:00min
> chore: run all needed karma tests in one session

- packages/building-webpack/README.md
- packages/building-webpack/modern-and-legacy-config.js
- packages/building-webpack/modern-config.js
- packages/create/src/generators/building-webpack/templates/static/webpack.config.js
I think this fixes the webpack generator/manual instructions, it doesn't seem to pick up the default options correctly though, need to dive into it more
> fix: default webpack generator config and docs

- docs/.vuepress/config.js
- docs/faq/unit-testing-init-error.md
I missed the PR that added this section but I have some improvements for this page, and added it to the sidebar menu as well. Deep dives need to be added in the .vuepress config file to show up in the sidebar
> docs: improve unit testing init error page

- docs/building/README.md
- packages/building-webpack/README.md
- packages/building-webpack/demo/js/index.html
- packages/building-webpack/demo/js/webpack.config.js
- packages/building-webpack/demo/js/webpack.modern.config.js
- packages/building-webpack/demo/ts-babel/index.html
- packages/building-webpack/demo/ts-babel/webpack.config.js
- packages/building-webpack/demo/ts/index.html
- packages/building-webpack/demo/ts/webpack.config.js
- packages/building-webpack/dom5-fork/README.md
- packages/building-webpack/dom5-fork/index.js
- packages/building-webpack/modern-and-legacy-config.js
- packages/building-webpack/modern-config.js
- packages/building-webpack/package.json
- packages/building-webpack/src/clean-up-html-loader.js
- packages/building-webpack/src/utils.js
- packages/create/src/generators/building-webpack/templates/_package.json
- packages/create/src/generators/building-webpack/templates/static/webpack.config.js
- Allows to use a single `input` HTML File for a webpack config
- This means that the same `index.html` file can be used with rollup/webpack/polymer server/owc-dev-server
- is backward compatible as there is a new config `input` if that one is used it overrides the entry and indexHTML
- uses pretty much the same code as found in rollup (parse5, dom5)
- parse5/dom5 could probably be ditched as we only need to take care of script tags (or we could try to align with the rollup config and offer a index.html to webpack/rollup config tool)
- adds all script src urls as a webpack entry point
- removes all script tags before passing it on to `HtmlWebpackPlugin`
=> this is a POC to show the idea  
=> I think this is really promising and we should promote it as the default way of using it (even …
> feat(building-webpack): enable single entry point html file

- docs/publishing/README.md
As requested, I've added a section to Publishing on how to serve using Apache. I've only been able to test this on localhost. (It will be over a week before I can try this on an internal network.)
> Added section on Serving With Apache HTTP Server

- docs/faq/component-libraries.md
As you can see [here](https://sap.github.io/ui5-webcomponents/), the name of the project is UI5 Web Components. :blush:
> docs: change library name

- packages/building-webpack/README.md
Spent a little trying to figure out the right `.babelrc` configuration for typescript by trying different manual combinations as specified in the linked babel docs. These are order and option-sensitive. Then I copied https://github.com/Polymer/lit-element/blob/master/.babelrc and things began to work.
If you're trying to use `LitElement` in typescript files with `@open-wc`-generator powered configs, this is what you'll need.
> docs: add LitElement-friendly .babelrc definition to webpack build page

- packages/building-rollup/plugins/rollup-plugin-modern-web/rollup-plugin-modern-web.js
- packages/building-rollup/plugins/rollup-plugin-modern-web/utils.js
Same fix to the same issue as in #344, except for the rollup build process as well.
> fix(building-rollup): support windows file paths

- packages/create/test/core.test.js
- packages/eslint-config/index.js
- packages/testing-helpers/test/elementUpdated.test.js
- packages/testing-helpers/test/stringLitFixture.test.js
- packages/testing/demo/test/get-result.test.js
- packages/testing/test/side-effects.test.js
disable
- `no-console` => useful especially in stories to show actions
- `no-unused-expressions` => mostly for tests to use `.to.be.true;`
- `class-methods-use-this` => mostly for tests when mocking
for test and stories files...
> fix(eslint-config): loosen up rules for test and stories files

- packages/create/src/generators/barebone-app/templates/_app.js
- packages/create/src/generators/testing/templates/_my-el.test.js
- packages/create/src/generators/wc-lit-element/templates/_MyEl.js
fixes https://github.com/open-wc/open-wc/issues/423
also changed `header` to `heading` because a `heading` is the content and `header` is the thing :D
> fix(create): fix tests in barebone-app

- packages/create/src/generators/testing-karma/templates/_package.json
The testing generator installs `1.x` version of `@open-wc/testing-karma` which does not properly handle the new syntax for karma files.
It causes IE11 tests to fail silently unless that package is updated to 2+
> FIX: install new testing-karma with generator

- docs/developing/README.md
- packages/building-rollup/README.md
- packages/building-webpack/README.md
- packages/create/src/generators/barebone-app/templates/_package.json
- packages/create/src/generators/barebone-app/templates/static/index.html
- packages/create/src/generators/building-rollup/templates/static/index.html
- packages/create/src/generators/building-rollup/templates/static/rollup.config.js
- packages/create/src/generators/building-webpack/templates/static/index.html
- packages/create/src/generators/building-webpack/templates/static/webpack.config.js
- packages/create/src/generators/starter-app/templates/static/index.html
Currently apps generated from `npm init @open-wc` have all source in the src directory.
This is rather weird when running with dev servers because the URL is similar to `http://localhost:8080/src/` and the `src` segment will be absent from production environment. It also applies to serving prod build with `http-server`.
With `index.html` placed in the root, there is no URL mismatch between environments.
> Move index.html to root of generated apps

- packages/testing-helpers/src/helpers.js
focus/blur helpers are flaky on IE11... let's see if we can improve it
> fix(testing-helpers): force focus/blur for IE

- packages/demoing-storybook/index.js
Storybook has a couple of knobs that are cool but not re-exported in open-wc, so here's a MR :).
> chore(demoing-storybook): add knob exports

- packages/building-rollup/plugins/rollup-plugin-modern-web/rollup-plugin-modern-web.js
This will benefit first load experience by not requiring the browser to traverse the module graph before initiating the request of these files.
fixes #472
> feat: include all static modules in `entryModules`

- packages/building-rollup/README.md
- packages/building-rollup/demo/ts-babel/demo-app.ts
- packages/building-rollup/demo/ts-babel/rollup.config.js
- packages/building-rollup/demo/ts/demo-app.ts
- packages/building-rollup/modern-and-legacy-config.js
I played around with the rollup setup for typescript, and after a lot of frustration, discovered that the rollup setup doesn't really support typescript (the demo code is just es6 with classes).
To reproduce this, add a type to the demo file, like this: `render(): TemplateResult {`,
and then run the ts-babel demo: `npm run build:ts-babel`.
You will then get the following error:
`[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)`.
To fix this, all that is needed is to add `extensions` option to `node-resolve` and `babel` plugins.
Not sure what the best approach would be for adding them, but thinking options?
TODO: docs when an approach has been picked
> Fix(building-rollup): add proper typescript support

- packages/building-rollup/plugins/rollup-plugin-modern-web/rollup-plugin-modern-web.js
Found an error when using the rollup **modern** setup in watch mode.
every time you change a file, there is be a bunch of systemjs imports at the bottom of the page, which should only have been used for the legacy setup.
Seems to be a straightforward logical `if else` error:
https://github.com/open-wc/open-wc/blob/a064acb30c21fac2b79911b001aa49a0362c41a7/packages/building-rollup/plugins/rollup-plugin-modern-web/rollup-plugin-modern-web.js#L243-L251
that should be solved by:
```
else if (pluginConfig.legacy && !writtenLegacyModules) {
```
To reproduce:
1. use this standard modern rollup config:
```
const createDefaultConfig = require('@open-wc/building-rollup/modern-config');
const config = createDefaultConfig({
input: './index.html'
});
```
2. run rollup in watch mode
3. inspect the index …
> fix(building-rollup): remove legacy scripts from modern watch mode

- packages/building-rollup/modern-and-legacy-config.js
When running watch mode using the legacy config, babel throws an error, since one of the plugins evaluates to falsy when not in production mode:
this is not the case for the modern config, since it filters out these plugins:
https://github.com/open-wc/open-wc/blob/6a0dce7ebd060c1d2a4c7c42a34ca8a9a8f22f6e/packages/building-rollup/modern-config.js#L33-L55
> fix(building-rollup): clean falsy plugins in legacy watch

- packages/building-rollup/modern-config.js
Recently there was a change to fix `ts-babel` builds https://github.com/open-wc/open-wc/pull/487
That change was only affecting `modern-and-legacy`, but not `modern`.
It should have been part of the first pr, but might also highlight some code duplication between the two 😄
> fix(building-rollup): make ts builds work for modern ts-babel

- karma.conf.js
- packages/import-maps-resolve/README.md
- packages/import-maps-resolve/babel.config.js
- packages/import-maps-resolve/package.json
- packages/import-maps-resolve/src/index.js
- packages/import-maps-resolve/src/parser.js
- packages/import-maps-resolve/src/resolver.js
- packages/import-maps-resolve/src/utils.js
- packages/import-maps-resolve/test/helpers/parsing.js
- packages/import-maps-resolve/test/parsing-addresses.test.js
- packages/import-maps-resolve/test/parsing-node-adoption.test.js
- packages/import-maps-resolve/test/parsing-schema.test.js
- packages/import-maps-resolve/test/parsing-scope-keys.test.js
- packages/import-maps-resolve/test/parsing-specifier-keys.test.js
- packages/import-maps-resolve/test/resolving-builtins.test.js
- packages/import-maps-resolve/test/resolving-node-adoption.test.js
- packages/import-maps-resolve/test/resolving-not-yet-implemented.test.js
- packages/import-maps-resolve/test/resolving-scopes.test.js
- packages/import-maps-resolve/test/resolving.test.js
code is a copy of the reference implementation with some adoption
- parse to string instead of javascript new URL (anticipate support for node paths)
- use es modules, mocha, chai instead of require, jest, jasmine
still todo:
> feat: package to parse and resolve import maps

- docs/faq/component-libraries.md
> docs(HelixUI): fix misspelling

- .circleci/config.yml
- package.json
- packages/building-utils/index-html/extract-resources.js
- packages/rollup-plugin-index-html/package.json
- packages/rollup-plugin-index-html/rollup-plugin-index-html.js
- packages/rollup-plugin-index-html/src/process-entry-html.js
- packages/rollup-plugin-index-html/test/fixtures/import-map/.gitignore
- packages/rollup-plugin-index-html/test/fixtures/import-map/app.js
- packages/rollup-plugin-index-html/test/fixtures/import-map/bar-fork/bar.js
- packages/rollup-plugin-index-html/test/fixtures/import-map/index.html
- packages/rollup-plugin-index-html/test/fixtures/import-map/node_modules/foo/foo.js
- packages/rollup-plugin-index-html/test/fixtures/import-map/node_modules/foo/index.js
- packages/rollup-plugin-index-html/test/fixtures/import-map/node_modules/lazy/index.js
- packages/rollup-plugin-index-html/test/fixtures/import-map/rollup.config.js
- packages/rollup-plugin-index-html/test/fixtures/import-map/shared.js
- packages/rollup-plugin-index-html/test/snapshots/import-map/app.js
- packages/rollup-plugin-index-html/test/snapshots/import-map/index-bcce6317.js
- packages/rollup-plugin-index-html/test/snapshots/import-map/index.html
- fixes some missing feature in import-maps/resolve
ToDo:
> feat(rollup-plugin-index-html): support import maps

- packages/building-webpack/modern-and-legacy-config.js
- packages/webpack-index-html-plugin/src/create-entrypoints.js
Closes https://github.com/open-wc/open-wc/issues/527
Closes https://github.com/open-wc/open-wc/issues/529
> fix(building-webpack): always export an array of configs

- packages/import-maps-generate/src/generate.js
- packages/import-maps-generate/src/generateFromYarnLock.js
- packages/import-maps-generate/src/postProcessImportMap.js
- packages/import-maps-generate/test/generateFromYarnLock.test.js
When applying an override, it adds an extra/unnecessary `.imports` property to the import map
After applying this fix:
> fix: subproperty bug

- packages/create/src/generators/app/index.js
- packages/es-dev-server/src/cli.js
- packages/es-dev-server/src/middleware/compatibility.js
- packages/es-dev-server/test/middleware/compatibility.test.js
- packages/eslint-config/index.js
- packages/eslint-config/package.json
- packages/import-maps-generate/src/findPathToVersion.js
- packages/import-maps-generate/src/findProductionDependencies.js
- packages/import-maps-generate/src/generate.js
- packages/import-maps-generate/src/generateFromYarnLock.js
- packages/import-maps-generate/test/findPackageJson.test.js
- packages/import-maps-generate/test/findPathToVersion.test.js
- packages/import-maps-generate/test/flattenYarnLock.test.js
- packages/import-maps-generate/test/generateFromYarnLock.test.js
- packages/import-maps-generate/test/injectToHtmlFile.test.js
- packages/import-maps-resolve/test/mergeImportMaps.test.js
- packages/semantic-dom-diff/index.js
- packages/testing-helpers/test/lit-html.test.js
- packages/testing-karma-bs/demo/test/example.test.js
- packages/testing-karma/demo/test/example-a.test.js
- packages/testing-karma/demo/test/example-b.test.js
- packages/webpack-import-meta-loader/test/caseB/index.js
- packages/webpack-import-meta-loader/test/webpack-import-meta-loader.test.js
BREAKING CHANGE: imports other than bare module specifiers now require their extensions to be explicitly set in the import, eg: `import foo from './bar.js';`
> feat(eslint-config): add import extensions linting rule

- docs/developing/ide.md
Currently linting section link is pointing to https://open-wc.org/developing/guide/linting which returns 404. It should point to https://open-wc.org/linting/
> docs: fix Linting section link

- packages/es-dev-server/README.md
- packages/es-dev-server/package.json
- packages/es-dev-server/src/command-line-args.js
- packages/es-dev-server/src/middleware/babel.js
- packages/es-dev-server/src/server.js
- packages/es-dev-server/test/fixtures/simple/src/excluded-legacy.js
- packages/es-dev-server/test/fixtures/simple/src/excluded-modern.js
- packages/es-dev-server/test/middleware/babel.test.js
- yarn.lock
This is needed for tests, as mocha, chai and sinon are large libraries and should not be compiled with babel.
> feat(es-dev-server): add option to prevent compiling files with babel

- docs/faq/component-libraries.md
Hey, I propose an entry in the faq/component-libraries for the components we built at Clever Cloud :wink:
> Add Clever Cloud's components in faq/component-libraries

- packages/rollup-plugin-index-html/src/create-entries-config.js
In a non-posix environment, the directory separator used is uri incompatible.
> fix missing '/' in legacy/[main].js in win32

- packages/es-dev-server/src/middleware/compatibility.js
In https://github.com/open-wc/open-wc/pull/555 we changed compatibility to longer require an app index, but polyfills were still expecting it to be set. This fixes that.
> fix(es-dev-server): serve polyfills correctly without app index

- packages/testing/package.json
BREAKING CHANGE: Removed the legacy flag which used webpack on older
browsers. We now use karma-esm everywhere which supports older
browsers with a compatibility option. For more details please see
the changelog of testing-karma and karma-esm.
> feat(testing): upgrade testing-karma to latest version

- packages/es-dev-server/src/middleware/compatibility.js
Polyfill paths refer to filepaths, which need to be transformed to browser path on windows.
Fixes https://github.com/open-wc/open-wc/issues/592
> fix(es-dev-server): resolve polyfill path on windows

- packages/es-dev-server/src/server.js
test reloading is broken because it doesn't set an app-index, which was still requires for browser reloading in the es-dev-server. We removed this requirement in the middleware, but we didn't remove the check when setting up the server.
> fix(es-dev-server): don't require app-index for reload

- docs/faq/component-libraries.md
Fixes: #617 
Remove AMP for lack of shadow dom support from the library listings.
> docs: remove amp for lack of support in shadow dom

- packages/create/src/generators/wc-lit-element/templates/static/.editorconfig
Use case:
Now I show you some code
```js
/**
* Block comment in my code example in my markdown
*/
function someFunc(foo) {
return `${foo}bar`; 
}
```
Basically without the EC rule, eclint would complain about the 2nd line ` * Block comment...` as well as the 3rd line ` */` because they only have 1 indent instead of 2 (according to indent-size)
> chore(create): change editorconfig to support md block comments

- karma.bs.conf.js
Browserstack connection is a bit flaky, increasing the timeout and adding retries seems to stabilize it quite a bit.
> increase browserstack CI timeouts

- packages/testing-karma/README.md
The code snippet under "Create a `karma.conf.js`" in the testing-karma README contained a [syntax error]. The `esm` option was not correctly nested in the second parameter given to the `merge` function. This PR fixes it by moving the `esm` option to the correct place.
[syntax error]: https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAExNgE5wCG8AInAGaECuANjAMLTkCWA5pgL6YC8mBAjlWYEAFAHIAAhAAOCALQB3MAHp4GZlFZyA1oTwBbQmICUAbgA6USFAyZ9cPKzg8+cQcLjiAJnDjT7jnAmFlCW+hBetHAAdHAAHtIQeDBoLtYs7NwAfNiWmLhMbNFocDAiefl2Dk4i+ESkFNR0jFAZtYWsxgA0uVCVlSw0cGhImADaFf35ysp8VDaYhDQ0mIPDmAheGuwKzDAAFpjRalgamAfOJ6sQND54XZNTM7iEfQBGzhAAbg4KeHvwd4AT0w0kIaDQ20WmDkclYBGkqxohFY0Q2cUI+mkQxGj36MzxlWeUH8cz6V1hMLhCPOwxgynIEAgyjeemOdOiACs0ITprMSfoybTbJTYfC-ML6ay8MoAFS87Cg4jwPBQUbpIrixEAfgKrU1NNGYhOctlcvZGC5aDEPRgQNkRvCk …
> docs(testing-karma): Fix incorrect code snippet in README

- packages/building-rollup/modern-and-legacy-config.js
- packages/building-rollup/modern-config.js
This PR tries to fix the override of default indexHTML options when you add new configuration through indexHTMLPlugin when you use modern and legacy rollup configuration.
Close #669
> fix(rollup-config): avoid default indexHTML options override

- docs/.vuepress/config.js
- docs/testing/testing-chai-dom-equals.md
> chore: remove chai-dom-equals page

- packages/create/src/core.js
Before this change, a subclasser making their own scaffolder would see the "for the same scaffold, use the following command:" displaying `npm init @open-wc` without the ability to change it to the name he wants to register the scaffolder as. Allowing this means they don't have to fork the core stuff for making custom generators / scaffolder outside of open-wc domain :)
> Allow subclassers to pass custom generator names

- packages/es-dev-server/README.md
- packages/es-dev-server/demo/base-path/index.html
- packages/es-dev-server/demo/base-path/module-a.js
- packages/es-dev-server/demo/base-path/module-b.js
- packages/es-dev-server/package.json
- packages/es-dev-server/src/command-line-args.js
- packages/es-dev-server/src/config.js
- packages/es-dev-server/src/create-middlewares.js
- packages/es-dev-server/src/middleware/base-path.js
- packages/es-dev-server/test/middleware/base-path.test.js
- yarn.lock
Some web apps are deployed on some base path, for example `/my-app/`. You want to be able to mimic this locally without needing to create a dummy folder called `my-app`. 
The `basePath` option allows you to configure this, it's basically a small middleware that strips that specific path from each requests before it's handled by the rest of the server.
> feat(es-dev-server): add option to set a base path

- packages/es-dev-server/package.json
- packages/es-dev-server/src/command-line-args.js
- packages/es-dev-server/src/config.js
- packages/es-dev-server/src/create-middlewares.js
- packages/es-dev-server/src/middleware/babel.js
- yarn.lock
Fixes https://github.com/open-wc/open-wc/issues/655
I opted for removing logging in the terminal entirely, and just leaving it to the browser. In the browser we see all the other kinds of errors already anyway, and it clears on reload so it's easy to keep of track of. 
Added some additional cleanup of the error messages.
> feat(es-dev-server): improve babel error logging

- packages/building-utils/index-html/polyfills.js
- packages/es-dev-server/package.json
- packages/es-dev-server/src/command-line-args.js
- packages/es-dev-server/src/config.js
- packages/es-dev-server/src/create-middlewares.js
- packages/es-dev-server/src/middleware/babel.js
- packages/es-dev-server/src/utils/polyfills.js
- packages/es-dev-server/src/utils/transform-index-html.js
- packages/es-dev-server/test/snapshots/transform-index-html/import-map-esm.html
- packages/es-dev-server/test/snapshots/transform-index-html/import-map-modern.html
- packages/es-dev-server/test/snapshots/transform-index-html/inline-module-esm.html
- packages/es-dev-server/test/snapshots/transform-index-html/inline-module-modern.html
- packages/es-dev-server/test/snapshots/transform-index-html/inline-module-none-babel.html
- packages/es-dev-server/test/snapshots/transform-index-html/simple-esm.html
- packages/es-dev-server/test/snapshots/transform-index-html/simple-modern.html
- yarn.lock
Fixes https://github.com/open-wc/open-wc/issues/685
- Don't polyfills webcomponents when esm mode is enabled (this was a bug)
- Fix typo in building-utils, placing es module shims inside the webcomponents if block
- Don't inject systemjs script unless in 'all' compatibility mode
> fix(es-dev-server): remove unnecessary polyfills in esm mode

- packages/create/src/Generator.js
This in addition my previous PR, will allow subclasser to just extend the Generator and change this.generatorName :). Prevents needing to fork Generator.js
> Allow extending Generator with name override

- packages/testing/README.md
Replace references to chai-dom-diff with semantic-dom-diff, as it was deprecated and then removed.
Related to #585 and #687
> docs(testing): remove references to chai-dom-diff

- packages/building-webpack/modern-and-legacy-config.js
- packages/building-webpack/modern-config.js
- packages/building-webpack/package.json
Allows overriding webpack mode through the config if set. Also defaults to production rather than development to match webpack's behavior.
Fixes https://github.com/open-wc/open-wc/issues/696
> feat(building-webpack): allow overriding mode through config

- packages/es-dev-server/src/middleware/transform-index-html.js
`URLSearchParams` is a global variable in node v10, but not in node v8. Importing it makes it work in both.
> fix(es-dev-server): import URLSearchParams for node v8

- packages/karma-esm/src/esm-middleware.js
We were missing a catch handler when starting up es dev server. This causes errors to not get logged, which was very confusing.
> fix(karma-esm): log errors starting up es-dev-server

- packages/webpack-index-html-plugin/src/create-entrypoints.js
The way we currently compute the entry filename is a bit native, if it doesn't end with an extension with two characters it leaves some characters behind. This change properly extracts any extension.
> fix(webpack-index-html-plugin): create entry without extension

- packages/create/src/generators/linting-eslint/templates/_package.json
In node a project should depend on anything it imports/uses directlry.
> fix(create): add eslint dependency in create

- packages/create/src/core.js
Prefix the console log message with the package manager name/command `npm: ` or `yarn: ` instead of `Error: ` because not all `stderr`'s are actually errors, and if they are, the `data` already has "ERROR" at the start.
Old
```
Error: notice <description>
Error: WARN <description>
Error: ERROR <description>
```
New:
```
npm: notice <description>
npm: WARN <description>
npm: ERROR <description>
```
"Fix" because users actually perceive this as a "real" error when sometimes it's just an npm warning or even an npm notice. Similar for yarn
> Fix: change installation logs prefix to package manager name

- packages/es-dev-server/src/utils/resolve-module-imports.js
- packages/es-dev-server/test/fixtures/simple/node_modules/@namespace/my-module-3/package.json
- packages/es-dev-server/test/snapshots/resolve-module-imports/string-concat-errors.js
- packages/es-dev-server/test/snapshots/resolve-module-imports/string-concatenation.js
- packages/es-dev-server/test/utils/resolve-module-imports.test.js
This supports expressions inside dynamic imports, as long as the package name is in the literal part of the string. See the test fixtures for some example use cases.
If we detect string concatenation and the import fails, we just return the path as is and let the imports resolve at runtime. This more user friendly, but probably a bundler will have issues resolving those paths.
> feat(es-dev-server): support resolving dynamic imports with expressions

- packages/building-utils/forked-babel-plugin-bare-import-rewrite.js
We removed the forked babel bare import rewrite plugin file since we no longer use it, but older versions of `karma-esm` rely on this and the change would not be picked up automatically through semver.
> fix(building-utils): re-add removed file

- packages/prettier-config/README.md
It looks like `lit-styles` is not actively developed and the docs haven't been updated to point to the `css` tag which is used by `lit-element`. Let's consider updating a link in README.
> chore(prettier-config): refer to lit-element css literal

- packages/es-dev-server/src/utils/message-channel.js
The logic around closing the previous and opening a new message channel (used for logging error messages + reloading the browser) wasn't correct. You can reproduce this by opening multiple tabs, it should close the channel on the old tabs and open it on the new tab.
> fix(es-dev-server): correctly close previous message channel

- docs/faq/component-libraries.md
Being open-wc has at least a passing relationship with the ING team, it's possible they want to add something additional to this description, like a "share your creations on Twitter" or something message, but otherwise, this puts this library pretty much on par with other listings.
> docs: add lion web components

- packages/es-dev-server/src/middleware/compile-middleware.js
In legacy mode we run babel twice in order to resolve modules on the es module source code. In this legacy run we don't need to add in any custom plugins again, so we can skip for a small saving.
> feat(es-dev-server): don't add custom plugins in legacy compile

- packages/semantic-dom-diff/get-diffable-html.js
- packages/semantic-dom-diff/test/get-diffable-html.test.js
affects: @open-wc/semantic-dom-diff
fixes: #782
> fix(semantic-dom-diff): strip empty class attrs when diffing

- packages/create/src/generators/building-webpack/templates/_package.json
Hello,
I think I fixed all wrong mode notations on create (#706). I made a search in the create folder on "mode" and "webpack".
Please tell me if I need to do something else !
Thanks
> fix(create): use standard webpack mode notation

- packages/es-dev-server/src/utils/message-channel.js
This fixes errors sometimes popping up in the console if you edit files after closing the browser in watch mode.
> fix(es-dev-server): don't send messages to a closed event stream

- docs/developing/routing.md
I have a created a light router for SPA -type applications built with Web Components. 
I would be honored if I could get it added to the list of routers for web component development.
> docs: Add Simplr Router to recommended routers

- packages/testing-karma/package.json
Looks like these 2 dependencies are leftovers from using `karma-webpack`
- `istanbul-instrumenter-loader` was used through webpack config,
- `karma-sourcemap-loader` was used through `preprocessors`.
Now when`karma-esm` is used, those packages can be removed.
> chore(testing-karma): remove unused dependencies

- packages/building-rollup/modern-and-legacy-config.js
Fix #874
I use `!legacy` to just create the SW in the second config, when the legacy files are already created.
> Generate the SW once with the createCompatibilityConfig

- docs/testing/testing-sinon.md
replaced el.shadowRoot.getElementByid with el.shadowRoot.getElementById
> Fixed the typo changed 'id' to 'Id'

- packages/semantic-dom-diff/get-diffable-html.js
- packages/semantic-dom-diff/test/get-diffable-html.test.js
Its an improvement of (#556). It strips attribute that contains only whitespace as a value.
> feat(semantic-dom-diff): strip attributes that contains only whitespace

- packages/demoing-storybook/index.js
Ehh yeah so I noticed this was not exported, even though it's already in the dependencies of demoing-storybook. I prefer exporting from one source (@open-wc/demoing-storybook) so would be awesome if you guys can export it so I can import from you guys :)!
Note: Registering the addon is already included in create -> generators -> demoing-storybook -> .storybook/addons.js so that's good ^^
Note 2: Was there a reason that addDecorator wasn't exported? I added it
> chore(demoing-storybook): export withA11y decorator

- .eslintrc.js
- package.json
- yarn.lock
say I wanted to test `es-dev-server`, I might change https://github.com/open-wc/open-wc/blob/dfd02845aa29fdd0f7ac9a44a184df9d5a836747/packages/es-dev-server/test/start-server.test.js#L9 from `describe` to `describe.only`.
when finished testing, if I forget to revert that change, I might end up accidentally committing it to master, which is dangerous, because no other tests will run.
This PR adds [`eslint-plugin-no-only-tests`](https://www.npmjs.com/package/eslint-plugin-no-only-tests) so that the linter will complain about any `.only` tests, suites, etc.
So now I'll get this error:
```
yarn run v1.16.0
$ run-p lint:*
$ prettier "**/*.{js,md}" "**/package.json" --check
$ eslint --ext .js,.html .
$ tsc
Checking formatting...
packages/es-dev-server/test/middleware/message-channel.test.js …
```
> chore: add eslint-plugin-no-only-tests

- package.json
The package.json pointed to the wrong file for "codelabs:build" script.
> fix: codelabs build correct path to build file

- packages/es-dev-server/src/create-middlewares.js
When you compress the event stream, watch mode doesn't work.
> fix(es-dev-server): don't compress event stream

- packages/testing-helpers/src/fixture-no-side-effect.js
- packages/testing-helpers/src/lib.js
- packages/testing-helpers/src/litFixture.js
- packages/testing-helpers/test/fixture.test.js
`render` from `lit-html` accepts more than just a `TemplateResult` nowadays.
testing-helpers can support string, number, boolean, TemplateResult,
Node, or Arrays or iterables of such.
Note: in the case of Array or Iterable, only the first child will be
taken. All others will be silently ignored. See https://github.com/open-wc/open-wc/issues/833
fixes: #716 
affects: @open-wc/testing-helpers
> feat(testing-helpers): allow rendering non-TemplateResult

- packages/create/src/generators/wc-lit-element/index.js
> fix(create): regression in app scaffolding when no options are selected

- package.json
- packages/prettier-config/package.json
- scripts/lint-versions.js
example output (= current situation)
```bash
$ npm run lint:versions
> @open-wc/root@ lint:versions /Users/ff67qn/html/open-wc
> node ./scripts/lint-versions.js
Version miss matches found in "./packages/building-rollup/package.json":
- "rimraf": "^3.0.0" !== "^2.6.3"
Version miss matches found in "./packages/building-utils/package.json":
- "rimraf": "^3.0.0" !== "^2.6.3"
Version miss matches found in "./packages/create/package.json":
- "rimraf": "^3.0.0" !== "^2.6.3"
Version miss matches found in "./packages/prettier-config/package.json":
- "prettier": "^1.18.2" !== "^1.15.0"
Version miss matches found in "./packages/rollup-plugin-index-html/package.json":
- "rimraf": "^3.0.0" !== "^2.6.3"
Version miss matches found in "./packages/webpack-index-html-plugin/package.json":
- "rimraf": …
```
> chore: lint alignment of all versions in the monorepo

- packages/es-dev-server/README.md
- packages/es-dev-server/demo/response-transformers/config.js
- packages/es-dev-server/demo/response-transformers/module-a.js
- packages/es-dev-server/demo/response-transformers/my-styles.css
- packages/es-dev-server/package.json
- packages/es-dev-server/src/config.js
- packages/es-dev-server/src/create-middlewares.js
- packages/es-dev-server/src/middleware/transform-response.js
- packages/es-dev-server/test/middleware/transform-response.test.js
- yarn.lock
This adds a new option to the dev server config to transform a response before serving. This has a number of use cases:
- An easier way to write transformations than custom middlewares. Easier for people to understand, and easier to hook into other tools.
- Serve virtual files, such as an auto generated storybook index.html
- Transform javascript **before** it goes through compatibility transforms.
- Light transformations, such as rewriting an app's base path
> feat(es-dev-server): add response transformers

- packages/es-dev-server/demo/node-resolve/module-a.js
- packages/es-dev-server/src/middleware/response-cache-middleware.js
Fixes https://github.com/open-wc/open-wc/issues/930
There are reports that the dev server sometimes doesn't serve an updated file correctly, I've seen this myself too locally. 
Right now we're fully reliant on chokidar / node's file system watching logic to receive events correctly. If we miss an event, the user sees the outdated version until restarting the server. There have been quite some bugs with chokidar in past, so I'd rather not rely on it entirely. 
With this change we're checking the file system's last modified timestamp before serving from cache. Unfortunately, we can't switch to this approach entirely and ditch chokidar because many file systems are not accurate to the millisecond so you can still end up with race conditions. We need chokidar anyway for watch mode, so doing …
> feat(es-dev-server): check last changed timestamp when caching

- packages/es-dev-server/src/utils/babel-compiler.js
`@babel/preset-env` should be resolved relative to es-dev-server location
> fix (es-dev-server): use `require` to resolve `@babel/preset-env`

- packages/codelabs/src/basics/lit-html.md
The number of arguments passed to the function assumes it should be setAttribute instead of getAttribute.
> setAttribute instead of getAttribute

- docs/building/README.md
Change "it's" to "its". See: https://www.google.com/search?q=plural+apostrophe&oq=plural+apostr&aqs=chrome.0.0j69i57j0l4.2340j0j1&sourceid=chrome&ie=UTF-8
> docs: building change it's to its

- .circleci/config.yml
💼 Cache your dependencies
🔑 Use your `yarn.lock` as a cache key
📦 Run `yarn install` only if no cache was found
🏅 Win time
PS: For us it was 54s to do yarn install vs 8s to restore cache => 84% faster 🎉
PPS: when there are no dep changes
> chore: cache dependencies on circleci

- docs/.vuepress/theme/components/Home.vue
- docs/.vuepress/theme/index.js
- package.json
- yarn.lock
closes #867
adds click-to-copy npm init @open-wc command to homepage, by creating a 
Vue child theme
> docs: add child theme with custom homepage

- packages/demoing-storybook/package.json
Resolves an issue when the stories source pattern was not being recognized due to incorrect interpretation of single quotes on Windows.
> fix(demoing-storybook): escape quotes in Storybook scripts

- packages/es-dev-server/demo/performance/server.js
- packages/es-dev-server/src/middleware/compatibility-transform.js
- packages/es-dev-server/src/middleware/message-channel.js
- packages/es-dev-server/src/middleware/response-body-cache.js
- packages/es-dev-server/src/middleware/response-transform.js
- packages/es-dev-server/src/middleware/transform-index-html.js
- packages/es-dev-server/src/utils/utils.js
When a request is cancelled, reading a response stream throws. This doesn't cause any issues, but it spams the terminal. This is especially apparent when working with larger applications.
This change handles this gracefully, reducing terminal spam.
Fixes https://github.com/open-wc/open-wc/issues/1010
> fix(es-dev-server): don't throw on cancelled requests

- packages/building-rollup/modern-and-legacy-config.js
- packages/building-rollup/modern-config.js
- packages/building-rollup/package.json
- yarn.lock
This removes the rollup hashmanifest plugin. 
This plugin hitchhiked along with a general change for hashing the entry file. I'm not sure we have an actual use case for the generated manifest. It generates in the current working directory, rather than the dist folder. Quite a few people have asked questions about what to do with this file, it feels pretty out of place.
Nowadays rollup has a great asset management API, so I don't think there is any need to have this in our config.
I don't consider this a breaking change, since you couldn't realistic use it outside of the dist folder.
> fix(building-rollup): remove hash manifest

- .github/stale.yml
If we add labels like bug or enhancement, we are acknowledging that it is a legitimate thing we want to add to our code/docs. In those cases, the stale bot shouldn't close the issue.
If an issue is missing a reproduction, or if things aren't clear yet, we do want the stale bot to intervene.
> chore: add more exempt stale labels

- packages/create/package.json
- packages/create/test/generate-command.js
- packages/create/test/integration.test.js
- packages/create/test/update-snapshots.js
closes #1032
adds a `test:update-snapshots` command to the create package which:
- executes the generator (in whichever state it's in, broken or not),
- then moves the output to the test/snapshots dir
- (**NB**: `--destination-path` option is broken see #1040 )
- does not generate the snapshot in packages/create/test/snapshots/fully-loaded-app.output.txt
I'd prefer to save that until after some refactors of the generator
> chore(create): add test:update-snapshots command

- packages/building-rollup/modern-and-legacy-config.js
- packages/building-rollup/modern-config.js
- packages/building-webpack/modern-and-legacy-config.js
- packages/building-webpack/modern-config.js
fixes #1049 
Update the config of `htmlMinifier` touse `conservativeCollapse: true` so that multiple whitespaces will get collapsed to one whitespace instead of none. This is of particular benefit when adjacent to non-known `display: inline` elements, as `htmlMinifier` attempts to do this by default for known elements.
> Use `conservativeCollapse` in the `htmlMinifier` config.

- packages/es-dev-server/README.md
- packages/es-dev-server/src/utils/resolve-module-imports.js
- packages/karma-esm/README.md
- packages/testing-karma/README.md
- Add mentions of `preserveSymlinks` option to `karma-esm` and `testing-karma` docs
- Improve `es-dev-server` doc
- Improve `preserveSymlink` related error message, to be more useful when it comes up while trying to run tests
> docs: document preserveSymlinks option

- docs/.vuepress/config.js
- docs/developing/lit-helpers.md
- packages/lit-helpers/LICENSE
- packages/lit-helpers/README.md
- packages/lit-helpers/index.js
- packages/lit-helpers/package.json
- packages/lit-helpers/src/spread.js
- packages/lit-helpers/src/spreadProps.js
- packages/lit-helpers/test/spread.test.js
- packages/lit-helpers/test/spreadProps.test.js
This introduces a new package, `@open-wc/lit-helper`, with two spread directives `spread` and `spreadProps`.
I considered adding `spreadAttributes`, but I felt that it wasn't needed because you can already use `spread` to do the same since there is no syntax difference for attributes.
Fixes https://github.com/open-wc/open-wc/issues/967
> feat(lit-helpers): add spread directives

- packages/create/src/generators/app/index.js
Since `scaffoldOptions` is initialized as an empty array, any arguments passed via command line get ignored by prompts, and do not get passed along to `this.options`.
This fix allows for setting that, like:
`npm init @open-wc --type scaffold --scaffoldType wc --features --scaffoldFilesFor demoing testing --installDependencies false --tagName`
For context, we are using this as an npm-run-script within a monorepo style component library, and would like to scaffold the story and test files, without the storybook and karma configs, since we have a root level test runner and Storybook instance.
> fix(create): support setting scaffoldFilesFor via command line argument

- docs/guide/component-libraries.md
HelixUi demo link can be found at https://github.com/HelixDesignSystem/helix-ui
It's now https://helixdesignsystem.github.io/helix-ui/
Previous link https://rackerlabs.github.io/helix-ui/ is returning 404
> docs: fix HelixUI link

- packages/es-dev-server/demo/syntax/index.html
- packages/es-dev-server/demo/syntax/module-features.js
- packages/es-dev-server/package.json
- packages/es-dev-server/src/utils/babel-transform.js
- packages/es-dev-server/test/integration/integration.test.js
- packages/es-dev-server/test/middleware/compatibility-transform.test.js
- yarn.lock
Apparently the module transform adds template literals in some situations, we need to compile those away for IE11.
Fixes https://github.com/open-wc/open-wc/issues/1083
> fix(es-dev-server): compile generated systemjs template literals

- packages/create/src/generators/building-rollup/templates/_package.json
Releases below 0 are treated as breaking changes, so we need to keep this in sync.
> feat(create): update building-rollup dependency

- packages/building-utils/index-html/create-index-html.js
- packages/building-utils/index-html/polyfills.js
- packages/es-dev-server/src/utils/polyfills-presets.js
- packages/es-dev-server/src/utils/transform-index-html.js
- packages/es-dev-server/test/integration/integration.test.js
- packages/es-dev-server/test/snapshots/transform-index-html/import-map-max.html
- packages/es-dev-server/test/snapshots/transform-index-html/inline-module-max.html
- packages/es-dev-server/test/snapshots/transform-index-html/simple-max.html
Loads regenerator runtime on modern browsers as well in max compat mode, this way you can use max compat as a fallback to work anywhere.
> feat(es-dev-server): allow max compat on modern browsers

- packages/semantic-dom-diff/README.md
In "Ignoring children" section the element name in markup is different from the passed to option
> docs: fix typo in semantic-dom-diff readme

- packages/karma-esm/README.md
- packages/karma-esm/demo/import-map/import-map.json
- packages/karma-esm/demo/import-map/karma.config.js
- packages/karma-esm/src/setup-es-dev-server.js
Currently importMap option passed to karma-esm is ignored (#1127)
This PR loads the importMap data and inject into karma debug and context files
It also fixes how chai path in test importmap is defined
The last part try to pass the flags to enable import map support in chrome based on [SO](https://stackoverflow.com/a/51070140). ~~This is not working~~. Using `--enable-experimental-web-platform-features` flag works
If i run Karma with Chrome and enable manually the importmap support it works
> fix(karma-esm): Implement import map support

- packages/karma-esm/src/setup-es-dev-server.js
The close body tag is being removed from final output when replacing it by script to inject tests. Browser automatically inserts but better safe than sorry.
> fix(karma-esm): add close body tag when injecting code to import tests

- packages/create/src/generators/app-lit-element/templates/static-testing/karma.conf.js
- packages/create/src/generators/testing-karma-bs/templates/static/karma.bs.config.js
- packages/create/src/generators/testing-karma/templates/_package.json
- packages/create/src/generators/testing-karma/templates/static/karma.conf.js
deepmerge  is smaller and is already a dependency of karma-esm
> fix(create): replace webpack-merge by deepmerge in testing dependencies

- packages/es-dev-server/README.md
- packages/es-dev-server/demo/dedupe/index.html
- packages/es-dev-server/demo/dedupe/index.js
- packages/es-dev-server/demo/dedupe/server.js
- packages/es-dev-server/package.json
- packages/es-dev-server/src/command-line-args.js
- packages/es-dev-server/src/config.js
- packages/es-dev-server/src/create-middlewares.js
- packages/es-dev-server/src/middleware/compatibility-transform.js
- packages/es-dev-server/src/utils/compatibility-transform.js
- packages/es-dev-server/src/utils/resolve-module-imports.js
- packages/es-dev-server/test/fixtures/simple/node_modules/my-module-2/node_modules/my-module/index.js
- packages/es-dev-server/test/fixtures/simple/node_modules/my-module-2/node_modules/my-module/package.json
- packages/es-dev-server/test/fixtures/simple/node_modules/my-module-2/node_modules/non-dedupable/package.json
- packages/es-dev-server/test/snapshots/resolve-module-imports/deduped-node_modules.js
- packages/es-dev-server/test/snapshots/resolve-module-imports/nested-node_modules.js
- packages/es-dev-server/test/snapshots/resolve-module-imports/none-dedupable.js
- packages/es-dev-server/test/snapshots/resolve-module-imports/relative-deduped-node_modules.js
- packages/es-dev-server/test/utils/resolve-module-imports.test.js
This adds a `dedupe` option to go along with https://github.com/open-wc/open-wc/pull/1000. The implementation is actually identical to the rollup implementation, because we're both using the same resolve package underneath. There are some limitations I'd like to see different, but I'd rather keep both options in sync and try to fix them on rollup's side too.
TODO:
> feat(es-dev-server): add module dedupe option

- packages/building-rollup/modern-and-legacy-config.js
- packages/building-rollup/modern-config.js
- packages/building-webpack/modern-and-legacy-config.js
- packages/building-webpack/modern-config.js
Module resolution in configuration files needs to use `require.resolve` when referencing modules, if they are to be correctly resolved at the point of configuration script execution. This PR adds these calls to correctly resolve modules according to node resolution scope used in `building-rollup` and `building-webpack` configurations.
> fix building module resolves

- packages/karma-esm/src/esm-middleware.js
The `karma-esm` configuration today has special case handling for serving snapshot markdown files directly from the `karma` web server rather than the `es-dev-server`. This is to allow the `karma-snapshot` plugin to do its thing and rewrite the Markdown files to JS.
However, the current implementation assumes a fixed path for the snapshot folder, but the `karma-snapshot` plugin supports rewriting this path using the `pathResolver` configuration.
This change will use that same `pathResolver` configuration to calculate the snapshot folder path if the config is present, otherwise will fallback to the previous assumed path.
> fix(karma-esm): modifies snapshot path to use pathResolver if configured

- packages/demoing-storybook/src/shared/listFiles.js
Changes in #1152 modified how file listing is done. This does however not capture all cases correctly.
Since the glob path passed to `listFiles` no longer has `rootDir` prepended to it, and since `glob` itself does not fully resolve the paths it returns relative to the `cwd` option, the paths are no longer correctly resolving in all cases.
This PR resolves each path against the root dir, before doing the directory check.
> fix(demoing-storybook): fixes story file listing

- packages/demoing-storybook/src/build/build.js
- packages/demoing-storybook/src/build/readCommandLineArgs.js
When building with storybook, it was always outputting `dist/sw.js`. This is because we aren't passing the output directory to the config generator.
> fix(demoing-storybook): pass outputdir to config generator

- docs/.vuepress/config.js
- docs/faq/README.md
- docs/faq/events.md
Not wanting great to be the enemy of good, this is a first iteration for the event usage recommendations. Namely, I stole @daKmoR's great TLDR and dressed it up a bit. This should allow us to close #1037 and have something to start sharing as needed.
fixes #1037 
refs #895 
For #895, I'd like to get into the nuance of some of the recommendations and plan to expand on this with further exposition in a later iteration. If we're in agreement, let's get this out and then I can start a separate PR for us to discuss the additional content or code labs, etc.
> docs: add initial events deep dive

- packages/testing-karma/src/create-default-config.js
This will make the pathResolver os agnostic. Previously, on Windows, the pathResolver would use `\` characters as delimiters for the path urls.
> fix(testing-karma): use an os-agnostic pathResolver

- packages/testing-helpers/README.md
- packages/testing-helpers/index.js
- packages/testing-helpers/src/helpers.js
- packages/testing-helpers/test/helpers.test.js
- packages/testing/index.js
Async rendering is quite a hassle, this helper helps manage this declaratively in tests and demos. I have a version of this that I use a lot in my own code.
> feat(testing-helpers): add waitUntil helper

- packages/es-dev-server/src/command-line-args.js
As discussed in https://github.com/open-wc/open-wc/commit/4085898bf9fd23ab51cd86d5fe582191c30be64e#r36748834, we introduced a breaking change by looking in the root dir for a config. In hindsight, this change was not needed for achieving what we need so we should revert it.
> fix(es-dev-server): don't look for config in root dir

- packages/testing-karma/package.json
- yarn.lock
fixes #1211 
Run tests with `--disable-dev-sgm-usage` as outlined in the setting for `karma-chrome-launcher@^3.1.0`.
> fix(testing-karma): latest karma-chrome-launcher decreases memory use

- packages/demoing-storybook/src/build/build.js
`!(node_modules|web_modules|bower_components|${outputRootDir})/**/custom-elements.json` will miss `custom-elements.json` files that are in the `rootDir` when building storybook. Update to `{,!(node_modules|web_modules|bower_components|${outputRootDir})/**/}custom-elements.json` to correct this.
> fix(demoing-storybook): allow custom-elements.json in rootdir

- packages/demoing-storybook/README.md
- packages/demoing-storybook/demo/.storybook/build-storybook.config.js
- packages/demoing-storybook/demo/.storybook/main.js
- packages/demoing-storybook/demo/.storybook/start-storybook.config.js
- packages/demoing-storybook/package.json
- packages/demoing-storybook/src/build/cli.js
- packages/demoing-storybook/src/build/readCommandLineArgs.js
- packages/demoing-storybook/src/shared/storiesPatternsToFiles.js
- packages/demoing-storybook/src/shared/storiesPatternsToUrls.js
- packages/demoing-storybook/src/start/cli.js
- packages/demoing-storybook/src/start/readCommandLineArgs.js
- packages/storybook-addon-web-components-knobs/package.json
alternative idea to 
https://github.com/open-wc/open-wc/pull/1227/
preread `main.js` and leave everything else as is... if we wanna go for that we would need to apply the same to the build
> feat(demoing-storybook): support main.js

- packages/demoing-storybook/README.md
Porting over my implementation to `main.js` and caught what is probably just a typo?
`outputPath` -> `outputDir`
> docs(demoing-storybook): config property name correction

- packages/demoing-storybook/src/build/build.js
- packages/demoing-storybook/src/shared/getAssets.js
- packages/demoing-storybook/src/start/cli.js
Resolve the location of `preview.js` and then resolve it relative to the web server root dir.
Also, fixes https://github.com/open-wc/open-wc/issues/1183
> fix(demoing-storybook): fix serving preview with a custom root dir

- packages/demoing-storybook/src/build/readCommandLineArgs.js
- packages/demoing-storybook/src/shared/storiesPatternsToFiles.js
I only upgraded `@open-wc/storybook` in a repo where `start-storybook.config.js` was used to define stories with a string and that failed...
=> move logic to convert to array where it is actually used (and not only for main.js)
> fix(demoing-storybook): allow stories string start-storybook.config.js

- packages/demoing-storybook/src/shared/getAssets.js
`storybook-build` no longer references my `preview.js` settings/code, and this seems to bring it back. It doesn't make any sense, because the import statement _should_ be 100% the same, but I prefer working code to code that I understand...apparently. Let me know if you can think of a better fix or a reason for this issue. The following branch of my project exhibits the issues I ran into https://github.com/adobe/spectrum-web-components/tree/westbrook/storybook-cleanup use `yarn storybook:build && npx http-server documentation/dist/storybook` to experience the issues when comparing to https://opensource.adobe.com/spectrum-web-components/storybook/?path=/story/action-menu--icon-only You'll see the padding is off in the demo, this is due to `sp-theme` being excluded from the demo HTML.
> fix(demoing-storybook): make preview.js available to storybook-build

- packages/demoing-storybook/README.md
Not sure if/how these links worked before but thinking they should be linked to (Open WC)[https://open-wc.org]
> Fix incorrect links in README

- packages/es-dev-server/src/middleware/history-api-fallback.js
- packages/es-dev-server/test/middleware/history-api-fallback.test.js
Validate only the url path, not the querystring, for . characters
to detect file paths.
> fix(es-dev-server): handle url parameters with . characters (#1059)

- packages/testing/index.d.ts
This type is currently missing, which requires the reliance on both `@open-wc/testing` and `@open-wc/testing-helpers` in a TS environment. Annoying.
> fix(testing): export "waitUntil" type

- packages/testing-karma-bs/README.md
Fixes a reference in the testing karma bs docs
Fixes the example code for karma.conf.bs.js to use `merge.all([...])` instead of `merge(...)` - https://www.npmjs.com/package/deepmerge#mergeallarrayofobjects-options
> docs: fix typos in testing-karma-bs

- packages/demoing-storybook/package.json
- packages/demoing-storybook/src/build/build.js
- packages/demoing-storybook/src/shared/getAssets.js
- packages/demoing-storybook/src/shared/injectStories.js
- packages/demoing-storybook/src/start/cli.js
- packages/demoing-storybook/src/start/transformers/createServeStorybookTransformer.js
We always had a race condition where the user's preview.js could be loaded before the user's stories. With the recent change of changing dynamic imports into static imports, this race condition is more likely to occur.
Moving this to a regular import makes the stories wait for the user's preview configuration.
> fix(demoing-storybook): always load user preview.js before stories

- packages/building-rollup/package.json
- packages/building-utils/package.json
- packages/building-webpack/package.json
- packages/chai-a11y-axe/package.json
- packages/codelabs/package.json
- packages/create/package.json
- packages/demoing-storybook/package.json
- packages/es-dev-server/package.json
- packages/eslint-config/package.json
- packages/import-maps-generate/package.json
- packages/import-maps-resolve/package.json
- packages/karma-esm/package.json
- packages/lit-helpers/package.json
- packages/polyfills-loader/package.json
- packages/prettier-config/package.json
- packages/rollup-plugin-index-html/package.json
- packages/scoped-elements/package.json
- packages/semantic-dom-diff/package.json
- packages/storybook-addon-web-components-knobs/package.json
- packages/testing-helpers/package.json
- packages/testing-karma-bs/package.json
- packages/testing-karma/package.json
- packages/testing-wallaby/package.json
- packages/testing/package.json
- packages/webpack-import-meta-loader/package.json
- packages/webpack-index-html-plugin/package.json
This way the "homepage" at at npmjs.com (e.g. https://www.npmjs.com/package/es-dev-server) will lead to the package-specific directory instead of the top-level monorepo. Useful for e.g. finding the CHANGELOG.
> Point package.json homepages to specific directories in monorepo

- .circleci/config.yml
🙈 Missed a dependency on the deploy step!
Running the CI now to see whether it looks better to have this in the workspace or to load the cache in the deploy step.
> ci: include node_modules in workspace

- packages/scoped-elements/README.md
- packages/scoped-elements/src/scoped-elements.js
- packages/scoped-elements/src/tag.js
- packages/scoped-elements/test/scoped-elements.test.js
- packages/scoped-elements/test/scoped-html.test.js
- packages/scoped-elements/test/tag.test.js
This commit uses the keys instead the class names for setting the tag names.
> fix(scoped-elements): unrecognizable tag names (#1293)

- packages/scoped-elements/README.md
Removed `}` from item number 4 in `Usage` section of `README.md`
> chore(scoped-elements): write valid html in example

- packages/scoped-elements/src/scoped-elements.js
- packages/scoped-elements/src/scoped-html.js
- packages/scoped-elements/src/transform.js
- packages/scoped-elements/test/scoped-elements.test.js
- packages/scoped-elements/test/scoped-html.test.js
- packages/scoped-elements/test/transform.test.js
This commit defers the definition of web components until they are used, so it allows to extend parent components without defining unused inherited web components.
> fix(scoped-elements): support extending elements (#1272)

- packages/create/src/generators/building-rollup/templates/_package.json
The building-rollup template still has version of building-rollup to ^0.15.0 --> latest matching is 0.15.4 which still relies on 0.4.x of rollup-plugin-terser which has a vulnerability.
The fix by you guys (updating the terser plugin) was done [here](https://github.com/open-wc/open-wc/pull/1124/files) and then later released as [0.16.0](https://github.com/open-wc/open-wc/blob/%40open-wc/building-rollup%400.16.0/packages/building-rollup/CHANGELOG.md#0160-2019-12-13) but the `create` package that provides package.json template wasn't updated to 0.16.x yet
So when I did `npm init @open-wc` and pick "building" with "rollup" and later pushed my stuff to github I got the security alert from GitHub that serialize-javascript has a vulnerability.
> fix(create): update building-rollup due to terser vulnerability

- package.json
- scripts/update-dependency.js
We have linter which enforces the same version of a dependency across the monorepo. This adds a script to easily update a dependency across all packages.
> chore: add script for updating a dependency in the monorepo

- packages/codelabs/src/intermediate/lit-html.md
references: as discussed in #1303 and #1310
- replace all occurances of NewsApp with BreweryApp
- replace all occurances of news-app with brewery-app
- replace all occurances of news-article with brewery-detail
- add json response object example for openbreweryDB api in section 3
- remove google news api specific api registration and api key from section 3
- add link to the brewery api and the documentation in section 3
- add additional notification block with link to the documentation of the
openbreweryDB api
- change the fetch functions jsonResponse. The jsonResponse contains the content
already, removing the .articles object property
- rename title and description from article items to name and type of brewery
- add additional brewery property city for the brewery-detail component
- …
> feat(codelabs): replace google news api with openbreweryDB api

- packages/demoing-storybook/src/build/build.js
Rollup can handle file paths in modules just fine, so I thought it was working fine on windows too. However the transform from es modules to systemjs breaks the import paths, and doesn't work on windows.
With this change, file paths are resolved changed to relative imports.
> fix(demoing-storybook): fix storybook build on windows

- docs/.vuepress/config.js
- docs/.vuepress/public/demoing/demo/custom-elements.json
- Make the nested menus non-collapsible. This makes it easier to see what's available and to jump between sections.
- Don't show page headings in the nav bar. It's a cool feature, but on some pages you really lose an overview of where you are. Our pages are usually pretty concise.
- Rename Tools to Tools & Libraries
- Move DedupeMixin to Tools & Libraries
> docs: make navbar more easily navigable

- packages/es-dev-server/src/create-middlewares.js
- packages/es-dev-server/src/create-server.js
Add default watcher to createMiddlewares
This will make the module function properly without a warning when used as a middleware.
Fixes #1315
> Add default watcher to createMiddlewares

- packages/building-utils/package.json
- yarn.lock
In order to use the latest version of `shady-css-scoped-element` as per this issue https://github.com/open-wc/open-wc/issues/1377
cc. @jrobinson01
> chore: update  shady-css-scoped-element version

- packages/building-rollup/README.md
- packages/building-utils/README.md
- packages/building-webpack/README.md
- packages/chai-a11y-axe/README.md
- packages/create/README.md
- packages/dedupe-mixin/README.md
- packages/demoing-storybook/README.md
- packages/es-dev-server/README.md
- packages/eslint-config/README.md
- packages/import-maps-generate/README.md
- packages/import-maps-resolve/README.md
- packages/karma-esm/README.md
- packages/lit-helpers/README.md
- packages/polyfills-loader/README.md
- packages/prettier-config/README.md
- packages/rollup-plugin-html/README.md
- packages/rollup-plugin-html/package.json
- packages/rollup-plugin-index-html/README.md
- packages/rollup-plugin-index-html/package.json
- packages/semantic-dom-diff/README.md
- packages/testing-helpers/README.md
- packages/testing-karma-bs/README.md
- packages/testing-karma/README.md
- packages/testing-wallaby/README.md
- packages/testing/README.md
- packages/webpack-import-meta-loader/README.md
- packages/webpack-index-html-plugin/README.md
- scripts/insert-header.js
The readmes for our packages were getting out of sync. Some didn't have the publish header, and some did have them but were missing the prepublish step to actually process them.
- Added missing publish headers and/or prepublish scripts
- Updated the publish header with the up to date project slogan.
- Moved the prepublish header below the project description. 
- Removed the `::tip::`, this feels like a double mention and takes up a lot of space. What do you think @daKmoR ? Does it add extra value? Maybe we should have it only for some projects, like the `configs` and not the `tools / libs` ?
> chore: align package readme files

- packages/es-dev-server/package.json
Adds dependency to package as listed in #1439. If this isn't the right path, let's discuss next steps in the issue.
fixes #1439
> fix(es-dev-server): add directly depended package to package.json

- packages/testing-helpers/index-no-side-effects.js
- packages/testing-helpers/index.js
Force a release of the `testing-helpers` package so that it picks up the types in CI now...
fixes #1438
> chore(testing-helpers): alphabetize exports

- .circleci/config.yml
- packages/testing-helpers/index-no-side-effects.js
- packages/testing-helpers/index.js
This persists _ALL_ files in all packages, which _should_ also include the definitions in sub dirs... 🤞 
fixes #1445 
fixes #1438
> fix(testing-helpers): publish typescript definition files again

- packages/scoped-elements/src/globalTagsCache.js
BREAKING CHANGE: getScopedTagName is not available anymore as a function but
                 a ScopedElementsMixin method.
> fix(scoped-elements): fix some jsDocs

- packages/semantic-dom-diff/README.md
The examples in `Setting up a snapshot` section are missing the `async` keyword in function declaration. This PR fixes that.
> chore: fix examples in Setting up a snapshot section

- packages/scoped-elements/src/ScopedElementsMixin.js
- packages/scoped-elements/test/ScopedElementsMixin.test.js
getScopedTagName should define the scoped element if it's not already defined.
fixes: https://github.com/open-wc/open-wc/issues/1455
> fix(scoped-elements): getScopedTagName returns undefined

- packages/scoped-elements/package.json
- packages/scoped-elements/src/ScopedElementsMixin.js
- packages/scoped-elements/src/shadyTemplateFactory.js
- packages/scoped-elements/test/ScopedElementsMixin.test.js
Instead transforming the ResultTemplates before render, this PR creates a scopedElementsTemplateFactory that is going to be used also by directives.
fixes: #1462
> fix(scoped-elements): elements not scoped using directives

- packages/demoing-storybook/demo/stories/docs-only.stories.md
- packages/storybook-addon-markdown-docs/demo/stories/docs-only.stories.md
- packages/storybook-addon-markdown-docs/package.json
- packages/storybook-addon-markdown-docs/src/mdjsToMd.js
- yarn.lock
this now allows images and line breaks in storybook... as if they don't have a closing tag the jsx parser throws 😭
> fix: support md images and line breaks in storybook

- .circleci/config.yml
- package.json
- packages/building-utils/index.js
- packages/building-utils/to-file-path.js
- packages/polyfills-loader/test/create-polyfills-loader.test.js
- packages/rollup-plugin-html/src/extractModules.js
- packages/rollup-plugin-html/src/getEntrypointBundles.js
- packages/rollup-plugin-html/test/fixtures/getInputHtmlData/index.html
- packages/rollup-plugin-html/test/rollup-plugin-html.test.js
- packages/rollup-plugin-html/test/src/extractModules.test.js
- packages/rollup-plugin-html/test/src/getInputHtmlData.test.js
- packages/rollup-plugin-polyfills-loader/test/rollup-plugin-polyfills-loader.test.js
I'm currently working on the new rollup config, and the plugins that go along with it. I want to make sure that they work on windows, so I added a windows step in the CI.
A lot of tests fail on windows, not necessarily because of bad code but often because of path and newline differences. For now I scoped it to the packages I'm working on, over time we can add more packages.
> chore: run tests on windows

- packages/create/src/generators/wc-lit-element/templates/_MyEl.js
Previous code set a specific variable value on `:host`, which does not make sense for variables since we probably want to allow overrides from ancestors.
> fix(create): set default value for variable

- packages/building-rollup/src/createSpaConfig.js
closes https://github.com/open-wc/open-wc/issues/1371
> feat(building-rollup): runtime cache polyfills

- packages/create/src/core.js
- packages/create/test/core.test.js
- packages/create/test/template/index.js
This change allows me to do the following:
```js
participants.forEach(name => {
copyTemplates(
'templates/**/*',
path.resolve(process.cwd(), `./participants/${name}`),
{ participantName: name },
).then(files => {
files.forEach(file => {
writeFileToPathOnDisk(file.toPath, file.processed, {
override: opts.override, // option that gets passed from my middleware, sometimes I need to override, sometimes I don't :P
ask: false,
});
});
});
});
```
Which is super awesome for generic purposes where I don't need a cli or the other cool features that, I assume, made you guys opt for a `virtualFiles` array that keeps the state in between functions.
Let me know if the test makes sense.. I couldn't really figure out a way to test copyTemplates without creating an actual template for testing. But …
> feat(create): copyTemplates resolves with the copied files

- packages/storybook-addon-markdown-docs/package.json
- wrong dependency @open-wc/demoing-storybook
should fix #1507
> fix(storybook-addon-markdown-docs): remove dep

- packages/rollup-plugin-html/README.md
> docs(rollup-plugin-html): fix syntax error in example

- packages/demoing-storybook/src/build/rollup/createRollupConfig.js
since we always compile to es5 now when building storybook, the regenerator runtime should always be loaded
> fix(demoing-storybook): ensure regenerator runtime is always loaded

- packages/es-dev-server/README.md
fixes #1519
This adds the `await startServer()` for clarity. To not further confuse (with the lack of top-level await) I wrapped the call in an async method. Let me know if you think of something that is more true to the functionality we're shipping here.
> docs(es-dev-server): clarify async nature of startServer

- docs/.vuepress/config.js
Missed some of the config settings in Vuepress for the updated "Deploying" page...  😥 
Adding back the sidebar.
> docs: add sidebar back to the deploying page

- packages/scoped-elements/README.md
Improves docs about scoped-elements
Fixes #1541
> docs(scoped-elements): add warning about self-defined elements

- docs/guide/README.md
Looks like this is a leftover from #1539
> chore: fix link for deploying in README

- package.json
- packages/building-rollup/package.json
- packages/building-rollup/src/createBasicConfig.js
- packages/demoing-storybook/package.json
- packages/demoing-storybook/src/build/rollup/createRollupConfig.js
- yarn.lock
For entrypoint modules rollup's default behavior is to preserve the original export signature.
One downside of this is that the exports add a (tiny) amount of unused code for web apps, since the entrypoint is never imported anywhere else. 
Another downside is that if the entrypoint bundle contains code used by other bundles, rollup needs to create an extra separate module which contains these exports. This is to not pollute the main entrypoint with exports it never included.
This behavior makes sense for libraries, but not for webapps. Rollup recently added a new option to configure this behavior. This PR adds this option by default to our configs.
This also adds a peerDependency to specify the version.
> feat(building-rollup): use new preserveEntrySignatures option

- docs/testing/testing-sinon.md
We need to await for rendering to complete before interacting with shadowRoot.
> docs(testing): update code example

- packages/scoped-elements/README.md
- packages/scoped-elements/src/registerElement.js
- packages/scoped-elements/test/ScopedElementsMixin.test.js
Reusing the global tag name can be useful in some situations in which not all component libraries are exporting the component classes or when components are looking in dom for specific tag names. In those cases, although this change doesn't remove the limitation of having just one version of those elements in our app, it makes them work properly inside our scoped elements as we are going to use the tag name they use in their definition.
E.g. If we want to migrate our app to scoped-elements but we are using `vaadin-grid` we are going to have problems because of vaadin components. We already have two options:
1- Ask or make a PR against vaadin components to change the way they interact with other components and making them "scoped friendly" (in the future, with scoped custom element …
> feat(scoped-elements): self-registering components compatibility

- packages/scoped-elements/index.js
- packages/scoped-elements/src/ScopedElementsMixin.js
- packages/scoped-elements/src/registerElement.js
- packages/scoped-elements/src/transform.js
- packages/scoped-elements/src/types.d.ts
- packages/scoped-elements/test/ScopedElementsMixin.test.js
- packages/testing-helpers/package.json
- packages/testing-helpers/src/fixture-no-side-effect.js
- packages/testing-helpers/src/litFixture.js
- packages/testing-helpers/src/scopedElementsWrapper.js
- packages/testing-helpers/src/stringFixture.js
- packages/testing-helpers/test/fixture.test.js
This PR allows to use scopedElements in fixtures with the following syntax:
```js
await fixture('<test-class foo="bar"></test-class>', {
scopedElements: {
'test-class': TestClass,
},
});
```
or
```js
await fixture(html`<test-class foo="bar"></test-class>`, {
scopedElements: {
'test-class': TestClass,
},
});
```
> feat(testing-helpers): add scoped-elements support

- packages/es-dev-server/src/create-server.js
Adds an HTTPS redirect when using es-dev-server in https mode.
> feat(es-dev-server): add https redirect

- packages/eslint-config/index.js
Karma uses `karma.conf.js` as the default configuration file name: http://karma-runner.github.io/4.0/config/configuration-file.html
This commit adds `'**/*.conf.js'` to the list of files that should accept dependencies as devDependencies, to support Karma config files.
> Allow more files to use devDependencies

- packages/testing-helpers/src/helpers.js
it should take a subclass of HTMLElement
> fix(testing-helpers): constrain the type of defineCE

- packages/eslint-config/README.md
I was upgrading my prettier to 2.0 and noticed there are some caveats with eslint that have been discussed on Slack and also seem to be integrated in the generators, but are not yet documented.
> chore(docs): add eslint-config-prettier to linting docs

- packages/building-rollup/src/createSpaConfig.js
After all, the legacy build browsers doesn’t support SWs.
> Run worbox only on the last output build

- packages/testing-helpers/package.json
- packages/testing-helpers/src/litFixture.js
In case scopedElements litFixture was awaiting element update of `node.firstElementChild`, which was `null`, instead of `node`.
> fix(testing-helpers): dependencies & await to the wrong element update

- packages/eslint-config/index.js
Adds `**/demo/**/*.js` to `devDependencies` of the `import/no-extraneous-dependencies` linting rule.
> fix(eslint-config): fixes open-wc/open-wc#1602

- docs/_includes/home.njk
- docs/_includes/layout.njk
- docs/_includes/partials/service-worker.njk
- docs/rollup.config.js
We need to have a new service worker in the same location and with the same name as our previous service worker for this to take effect, which is why I overrided the default workbox config.
What happens now is that every page will try to register a service worker. If there is a new service worker available, it'll skip waiting, and on controllerchange reload the page.
Would like someone else to confirm to make sure:
Steps:
- Run a build: `yarn docs:build`
- `cd _site && http-server -o` (dont use the Eds configuration for this, because it configures a base path)
- Go the page, confirm service worker is installed (devtools -> application -> Service Workers “#0 activated and is running”)
- Close the tab.
- Make some changes in a readme or anything in the docs
- Run another build: `cd .. && …
> WIP: docs: pwa-ify and update on reload

- packages/rollup-plugin-html/src/utils.js
When the rollup entrypoint is an object, we should set a valid entrypoint instead of the full file path.
> fix(rollup-plugin-html): set a valid entrypoint name

- docs/_data/site.js
Updates the URL of the build based on this documentation: https://docs.netlify.com/configure-builds/environment-variables/#deploy-urls-and-metadata Please give another eye to it in case you think I've misread.
> docs: apply specific type of URL by deploy type

- packages/create/src/generators/app-lit-element-ts/templates/_tsconfig.json
- packages/create/src/generators/wc-lit-element-ts/templates/_tsconfig.json
Generates a separate .js.map file in out-tsc/ that has the original TS source inlined in it.
This should let us see the original TS source while debugging.
Browser is able to load the sourcemap when used in development mode with es-dev-server.
Currently not being processed by rollup in production mode and the behavior is same as earlier.
> fix(create): generate sourcemap for ts files

- packages/create/src/core.js
- packages/create/test/core.test.js
In our extension of the open-wc scaffolder we allow an option which has type = number, because we allow our users to pick which version of our design system they want to scaffold files for.
With this change, the scaffolder will tell the user they can mimic their interaction in the scaffold menu by running it imperatively with the flag `--designSystemVersion 2`, but because currently type 'number' is not supported here, it will skip it.
> fix(create): support number for optionsToCommand

- packages/lit-helpers/src/spreadProps.d.ts
previous type was needlessly narrow, it would error on:
```ts
const tpl = (opts?: TemplateOpts) => html`<x-l ...="${spreadProps(opts ?? {})}"></x-l>`;
```
> fix(lit-helpers): spreadProps typings

- docs/faq/events.md
Clarify that `.bind` is not necessary to call when attaching an event via `addEventListener` to the element
> docs: update events.md

- packages/es-dev-server/src/config.ts
- packages/es-dev-server/src/create-middlewares.ts
- packages/es-dev-server/src/plugins/babelTransformPlugin.ts
- packages/es-dev-server/src/utils/compatibility-transform.ts
This allows configuring custom babel include/exclude. We need this when using a babel plugin for test coverage, so that we can restrict the amount of files babel runs on. Improving speed.
> feat(es-dev-server): allow configuring custom babel include/exclude

- packages/testing-karma/src/create-default-config.js
After a lot of debugging, I found out that there is a race condition inside the karma browser client where sometimes it cancels a test run right after a reload when the `restartOnFileChange` option is set. 
Disabling this makes it more stable, but you have to wait for a test run to finish before rerunning tests again.
> fix(testing-karma): disable restartOnFileChange option

- packages/testing-helpers/src/scopedElementsWrapper.js
Loading multiple instances of the testing package could cause a naming collision in the ScopedElementsTestWrapper definition. Auto-generating the tag name and checking that it is not used in the global registry before definition solves the problem.
Fix: #1637
> fix(testing-helpers): auto-generate scoped elements test wrapper name

- packages/building-rollup/package.json
> fix(building-rollup): add `regenerator-runtime` dependency explicitly

- packages/es-dev-server/src/browser-scripts/message-channel.ts
The inlined script on message-channel.ts is not transpiled. This code was using
the arrow function which was failing in ES5 only browsers like IE11.
The fix is to use non-arrow anonymous function similar to rest of the script.
Tested manually with IE11.
> fix(es-dev-server): fix messagechannel to be ES5 compatible

- docs/publishing/index.md
Hello!
Just fixing up a typo I spotted in the Publishing docs: `Componoent` => `Component`
> chore(docs): update typo in publishing docs

- docs/linting/README.md
- package.json
- packages/create/owc-app/package.json
- packages/create/src/generators/linting-ts/templates/_package.json
- packages/create/src/generators/linting/templates/_package.json
- packages/create/test/snapshots/fully-loaded-app/package.json
- yarn.lock
This resolves deprecation warnings when installing the dependencies of the generated project.
For consistency, I upgraded the version wherever applicable.
> chore: upgrade to lint-staged@10

- packages/es-dev-server/src/plugins/nodeResolvePlugin.ts
This will fix the `nodeResolvePlugin` for absolute Windows paths, in the same as for the es-dev-server-rollup extension: https://github.com/LarsDenBakker/es-dev-server-rollup/pull/3
> fix(es-dev-server): allow absolute Windows paths in `nodeResolvePlugin`

- docs/developing/types.md
The mentioned issue has been fixed in TypeScript 3.7
> docs: remove obsolete note about `allowJs` issue

- packages/testing-helpers/src/helpers.js
Fixes #1460 
* Changed default timeout for `waitUntil` to `1000`ms
* Added given `timeout` to error
> fix(testing-helpers): change default timeout to 1000ms for waitUntil

- packages/es-dev-server/test/snapshots/polyfills-loader/max.html
- packages/polyfills-loader/index.js
- packages/polyfills-loader/src/create-polyfills-data.js
- packages/polyfills-loader/src/create-polyfills-loader.js
- packages/polyfills-loader/src/types.d.ts
- packages/polyfills-loader/test/create-polyfills-data.test.js
This commit also:
- introduces ordering when defining polyfills
- allows explicit inclusion of systemjs polyfill
- makes files optional when defining configs
> feat(polyfills-loader): expose `create-polyfills-data`

- docs/guide/component-libraries.md
This PR adds [FAST](https://fast.design) as a new web component library to the open-wc site and closes this tweet: https://twitter.com/WestbrookJ/status/1290626892031238146?s=20 😄
> docs(libraries): add FAST as a new web component library

- docs/guide/component-libraries.md
An extra tab in the source file causes the FAST library list item to be indented and rendered as a sub-bullet.
> docs(component-libraries): remove extra tab

- packages/scoped-elements/README.md
- packages/scoped-elements/src/transform.js
- packages/scoped-elements/test/transform.test.js
This change adds the attribute `data-tag-name` to each scoped element with the unscoped tagName.
In relation with #1751, this data attribute could be used to select scoped elements in e2e tests predictively.
> feat(scoped-elements): add data-tag-name with the original tagName

- packages/eslint-config/package.json
To better support ESLint v7 peerDep resolution.
See: https://github.com/open-wc/open-wc/issues/1739
==
When we extend `open-wc/eslint-config` and install it on a project, the various plugins found in `dependencies` are not resolved by ESLint v7:
```json
"dependencies": {
"eslint-plugin-babel": "^5.3.0",
"eslint-plugin-html": "^6.0.0",
"eslint-plugin-import": "^2.18.2",
"eslint-plugin-lit": "^1.2.0",
"eslint-plugin-no-only-tests": "^2.4.0",
"eslint-plugin-wc": "^1.2.0"
}
```
Therefore, we have to manually install each plugin individually as a `devDependencies` for each project that extends `open-wc/eslint-config`.
You'll notice that the `airbnb-base` config includes `plugin-import` in `peerDependencies` and they refer to installing peerDeps in their …
> feat(eslint-config): Improve ESLint v7 support by adding plugins to peerDeps

- packages/rollup-plugin-html/rollup-plugin-html.js
- packages/rollup-plugin-html/src/extractModules.js
- packages/rollup-plugin-html/test/rollup-plugin-html.test.js
- packages/rollup-plugin-html/test/src/extractModules.test.js
The HTML plugin has a bug where inline modules from different HTML files could end up with the same id if two HTML files have the same name.
I considered using UUIDs, but that would make testing harder. Keeping a counter is sufficient here.
> fix(rollup-plugin-html): ensure inline module ids are unique

- packages/scoped-elements/src/transform.js
This commit replaces `startsWith` by `indexOf` to make it work on ie11 without requiring a polyfill.
Fixes #1809
> fix(scoped-elements): make code ie11 compatible

- packages/semantic-dom-diff/get-diffable-html.js
- packages/semantic-dom-diff/test/get-diffable-html.test.js
The `semantic-dom-diff` package currently does not escape attributes that received previously escaped attribute values. As such, the resulting HTML from the `getDiffableHTML` function is not valid:
```
✖ 1 test failed
FAILED TESTS:
getDiffableHTML()
attributes
✖ escapes attributes that require it
Chrome Headless 84.0.4147.105 (Linux x86_64)
AssertionError: expected '<div\n  a="i "have" quotes"\n  b="attributes & values"\n>\n</div>\n' to equal '<div\n  a="i &quot;have&quot; quotes"\n  b="attributes &amp; values"\n>\n</div>\n'
+ expected - actual
<div
-  a="i "have" quotes"
-  b="attributes & values"
+  a="i &quot;have&quot; quotes"
+  b="attributes &amp; values"
>
</div>
at Context.<anonymous> (packages/semantic-dom-diff/test/get-diffable-html.test.js:345:23)
at Test.Runnable.run …
```
> fix(semantic-dom-diff): fix unescaped attributes

- docs/_includes/partials/service-worker.njk
This solves @daKmoR frustration
How to try it locally:
- `npm run docs:build`
- `cd _site && http-server -o`
- open docs in browser
- make a change to `docs/about/README.md` (add some dummy text, so long as its byte different)
- `cd .. && npm run docs:build`
- `cd _site && http-server -o`
- go to browser, refresh, **quickly** open a menu item
- once the new service worker has taken over, you should still see the menuitem being open
Example:
> docs: retain opened menu items when new sw has taken over and refreshed

- packages/mdjs/src/mdjsProcess.js
- packages/mdjs/test/mdJsProcess.test.js
What I did:
- deprecate the `mdjsProcessPlugins` exports
- deprecate the `plugins` options for `mdjsProcess`
- add `setupUnifiedPlugins` which can be a function or an array of functions to modify the unified plugins
=> prerequisite for a `eleventy-plugin-mdjs`
> feat(core): replace exporting plugins array with setup functions

- packages/chai-a11y-axe/package.json
- packages/testing-karma/package.json
- yarn.lock
Update `axe-core` to latest [major release](https://github.com/dequelabs/axe-core/releases/tag/v4.0.0) to pull in latest accessibility rules.
> chore: update axe-core to 4.x

- packages/testing-helpers/src/scopedElementsWrapper.js
This is needed because different typescript versions seem to either throw or not throw, inconsistently. This makes expect-error problematic for users with typescript versions that don't throw on this. Review when the TS issue is closed by typescript.
fixes https://github.com/open-wc/open-wc/issues/1826
> fix(testing-helpers): replace ts-expect-error with ignore

- packages/semantic-dom-diff/README.md
- packages/semantic-dom-diff/get-diffable-html.js
- packages/semantic-dom-diff/test/get-diffable-html.test.js
Hey guys!
It's me again, trying to improve our `semantic-dom-diff` package to better process scoped elements.
I realised... why put the burden on devs to get the real names of scoped elements' tags when using diff options? It's important they know, but snapshots shouldn't care that much. I myself ended up with a test which looked like this:
```js
const getScopedTag = (el, tag) => el.constructor.getScopedTagName(tag, el.constructor.scopedElements)
const domDiffConfig = (el) => {
return {
ignoreChildren: [
getScopedTag(el,'ing-input-amount'),
getScopedTag(el,'ing-select'),
getScopedTag(el,'ing-labs-spinner')
],
ignoreAttributes: [
getScopedTag(el,'ing-labs-spinner')
]
}
}
```
I improved my previous contribution, from `getLocalName` to `getTagName` which will work both for  a `Node` or …
> feat(semantic-dom-diff): diff options now process scoped elements

- packages/es-dev-server/test/snapshots/polyfills-loader/inline-scripts-exclude.html
- packages/es-dev-server/test/snapshots/polyfills-loader/inline-scripts-resolve-imports.html
- packages/polyfills-loader/src/create-polyfills-data.js
This removes the source map URL from polyfills because they're causing 404s. We could look into including source maps later if needed.
> fix(polyfills-loader): remove source map URL

- packages/testing-karma/README.md
After #1556, as stated by @Westbrook on #1164, the `coverageReporter` `global` setting is now defined inside the `check` attribute instead of the `thresholds`  :)
> docs: testing karma coverage check

- packages/eslint-plugin-lit-a11y/template-analyzer/template-analyzer.js
fixes https://github.com/open-wc/open-wc/issues/1891
before:
after:
> fix: report errors on correct location, not entire quasi

- packages/eslint-plugin-lit-a11y/lib/rules/aria-role.js
- packages/eslint-plugin-lit-a11y/template-analyzer/util.js
- packages/eslint-plugin-lit-a11y/tests/lib/rules/aria-attr-valid-value.js
- packages/eslint-plugin-lit-a11y/tests/lib/rules/aria-role.js
fixes #1889
Maybe just "refs" #1889, but this allows for the following syntaxes to lint:
```
<input aria-valuemax=${this.max} />
<input aria-disabeld=${this.disabled ? 'true' : 'false'} />
```
Currently is replaces it with a placeholder, but I can see room (and reason) to want to follow these tests/properties down their path to ensure that the actual typings of the binding that they represent are achieved.
> fix(eslint-plugin-lit-a11y): support member and conditional expressions

- packages/eslint-plugin-lit-a11y/docs/rules/accessible-emoji.md
- packages/eslint-plugin-lit-a11y/docs/rules/alt-text.md
- packages/eslint-plugin-lit-a11y/lib/index.js
- packages/eslint-plugin-lit-a11y/lib/rules/accessible-emoji.js
- packages/eslint-plugin-lit-a11y/lib/rules/alt-text.js
- packages/eslint-plugin-lit-a11y/lib/utils/elementHasAttribute.js
- packages/eslint-plugin-lit-a11y/lib/utils/isHiddenFromScreenReader.js
- packages/eslint-plugin-lit-a11y/tests/lib/rules/accessible-emoji.js
- packages/eslint-plugin-lit-a11y/tests/lib/rules/alt-text.js
allows
```js
html`
<div role="img" aria-label="foo"></div>
<div role="img" aria-labelledby="label"></div>
`;
```
also allows
```js
html`
<span role="img" alt="Panda">🐼</span>
`
```
> fix(eslint-plugin-lit-a11y): aria-label img role

- packages/eslint-plugin-lit-a11y/lib/rules/aria-attr-valid-value.js
- packages/eslint-plugin-lit-a11y/lib/rules/aria-role.js
- packages/eslint-plugin-lit-a11y/lib/rules/tabindex-no-positive.js
- packages/eslint-plugin-lit-a11y/template-analyzer/util.js
- packages/eslint-plugin-lit-a11y/tests/lib/rules/aria-role.js
- packages/eslint-plugin-lit-a11y/tests/lib/rules/img-redundant-alt.js
- packages/eslint-plugin-lit-a11y/tests/lib/rules/tabindex-no-positive.js
Reverting the custom placeholder logic for now. We could revisit this in the future, but currently there are many edgecases that we miss, and it also throws a spanner in the works with regard to reporting in the correct location. I think its better if we iterate on this in a later version, and then we could potentially also upstream it to eslint-plugin-lit. But to get an initial version out of the door, I think its good enough to simply ignore expressions for now.
The consequence of this change is that we no longer check simple literal values in expression `<div tabindex=${0}>`, for example.
> fix: revert custom placeholder logic

- docs/_data/footer.json
1. Changed "Github" to "GitHub" in the site footer.
> Properly capitalize "GitHub" in site footer

- .changeset/eighty-sheep-agree.md
- packages/scoped-elements/README.md
- packages/scoped-elements/src/Cache.js
- packages/scoped-elements/src/ScopedElementsMixin.js
- packages/scoped-elements/src/globalTagsCache.js
- packages/scoped-elements/src/registerElement.js
- packages/scoped-elements/src/transform.js
- packages/scoped-elements/test-web/Cache.test.js
- packages/scoped-elements/test-web/ScopedElementsMixin.test.js
1. Allows lazy components to be defined by scoped element instances instead of by scoped elements classes.
this change makes scoped elements to be more aligned with the scoped registries proposal.
> feat: define lazy components by element instance instead of by class

- .changeset/plenty-plants-hunt.md
- packages/scoped-elements/src/Cache.js
- packages/scoped-elements/test-web/Cache.test.js
1. Refactored code to improve tooling support. Optional chaining isn't fully supported yet (namely webpack 4). Though it does look like most tools are "close" to it.
2. Addresses https://github.com/open-wc/open-wc/issues/1979
> fix(scoped-elements): refactor to remove optional chain in Cache

- docs/_data/baseLibraries.js
1. Add DataFormsJS Web Components https://www.dataformsjs.com/ to data file so they can appear in https://open-wc.org/guides/community/base-libraries/
> Add DataFormsJS to [docs/_data/baseLibraries.js]

- docs/docs/index.md
1. Added a list of top level pages in the Documentation section to prevent mobile entry to the section to look empty.
> docs: ensure that landing on the docs page does not strand mobile users

- docs/docs/demoing/storybook.md
1. After moving create package in another repositories, a link in storybook.md isn't up to date.
> doc: Update link to storybook templating folder

- .changeset/stale-ways-unite.md
- packages/dev-server-hmr/demo/fast-element/src/todo-app.ts
- packages/dev-server-hmr/src/presets/haunted.js
- packages/dev-server-hmr/src/wcHmrRuntime.js
When using a proxy, the `.prototype` property must always return the original value. This is a problem when modification the prototype, this happens for example when decorators are compiled away. 
I updated the HMR runtime to return a new proxy each time a class is replaced. We also need to update references to the `constructor` to this new proxy, to keep things in sync.
> fix(dev-server-hmr): allow prototype modification

- .changeset/wise-mayflies-buy.md
- packages/eslint-config/index.js
Allow MJS and TS file extensions in some of the eslint config overrides.
> feat(eslint-config): add MJS and TS extensions

- .changeset/metal-hats-fly.md
- packages/lit-helpers/package.json
1. widened the peerDependencies version constraints for lit-element and lit-html in the `lit-helpers` package
> fix(lit-helpers): peer dependency versions

- .changeset/clean-impalas-study.md
- packages/scoped-elements/src/types.d.ts
In short: In order to implement the mixin in a LitElement, which has a constructor, the scoped elements host (base class) also needs a constructor with the same return type (void I guess?). Otherwise TSC will scream at you. 
More details: https://github.com/microsoft/TypeScript/issues/40110
> fix(scoped-elements): add constructor to type definition

- .changeset/unlucky-rings-relax.md
- packages/dev-server-hmr/src/wcHmrRuntime.js
fixes: https://github.com/modernweb-dev/web/issues/1177
1. I added a check for the constructor of the `WebComponentHmr` class so that it doesn't assume that the class the component is an instance of was actually registered in the `keysForClasses` map
When delving into https://github.com/modernweb-dev/web/issues/1177 , I found out that the reason for the problems mentioned there were:
- [The way scoped-elements creates a class that extends the original class](https://github.com/open-wc/open-wc/blob/master/packages/scoped-elements/src/registerElement.js#L21)
- The way data is stored and accessed in the [`keyForClasses` map in wcHmrRuntime](https://github.com/open-wc/open-wc/blob/master/packages/dev-server-hmr/src/wcHmrRuntime.js#L92)
From what I've been able to understand, the `register` …
> fix(dev-server-hmr): fix compatibility with scoped-elements

- docs/docs/building/rollup.md
Copy pasted the snippet tonight and got a bit of a surprise: 
```
./index.html → dist...
[!] (plugin copy) Error: EROFS: read-only file system, mkdir '/dist'
Error: EROFS: read-only file system, mkdir '/dist'
npm ERR! code 1
npm ERR! path /Users/jlengrand/Developer/paper-dashboard
npm ERR! command failed
npm ERR! command sh -c rimraf dist && tsc && rollup -c rollup.config.js
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jlengrand/.npm/_logs/2021-02-02T23_00_23_984Z-debug.log
```
A little scary ?! :)
1.
> Use relative path in snippet instead of absolute

- .changeset/good-starfishes-brake.md
- packages/building-rollup/package.json
- packages/building-rollup/src/babel/babel-configs.js
Now Rollup already support it.
- https://github.com/rollup/rollup/pull/3582
- https://github.com/rollup/rollup/pull/3548
> chore(deps): remove unneeded babel plugins

- docs/guides/developing-components/publishing.md
1. Added a simple optional React section to the publishing guide [as discussed here](https://github.com/open-wc/open-wc/discussions/2100)
> docs: add react section to publishing guide

- docs/guides/tools/ide.md
1. Added some documentation on setting up a open-wc supporting dev environment on Vim/Neovim
> docs: Add vim documentation to IDE page

- .changeset/tender-spies-hear.md
- packages/eslint-config/index.js
Added `html` extension to the config for excluding rules in test folders. This will allow me to write test files with [@web/dev-server-import-maps](https://modern-web.dev/docs/dev-server/plugins/import-maps/) (which requires using HTML files) without getting ESLint errors.
> feat(eslint-config): add HTML extension

- docs/docs/testing/helpers.md
1. Updated helpers.md to include the correct default timeout for `waitUntil`.
> Update helpers.md to include correct timeout

- README.md
- previously called Polymer slack
> Update Lit & Friends slack links

- .changeset/gorgeous-hotels-lay.md
- packages/scoped-elements/package.json
1. Mark `loadPolyfill.js` as a side effect.
Fixes #2156
> fix(scoped-elements): mark loadPolyfill.js as a side effect

- .changeset/slow-parents-develop.md
- packages/scoped-elements/src/ScopedElementsMixin.js
1. `getScopedTagName(tagName: string): string` now returns the tag passed in
Fixes #2157
> fix(scoped-elements): getScopedTagName returns the tag passed in

- package.json
- yarn.lock
1. The service worker no longer precaches all urls and assets. It now
- caches already visited pages
- caches assets of visited pages (up to 100 files then it replaces older entries)
- on service worker activation it will reload the page if a newer version is available
> chore: update service worker strategy to cache only visited

- .changeset/old-chefs-wink.md
- packages/scoped-elements/src/ScopedElementsMixin.js
- packages/scoped-elements/test-web/ScopedElementsMixin.test.js
1. keep deprecated static getScopedTagName function
> fix(scoped-elements): keep deprecated static getScopedTagName function

- .changeset/nasty-humans-promise.md
- docs/blog/testing-workflow-for-web-components/index.md
- docs/docs/linting/eslint-plugin-lit-a11y/rules/no-invalid-change-handler.md
- packages/eslint-plugin-lit-a11y/docs/rules/no-invalid-change-handler.md
- packages/eslint-plugin-lit-a11y/lib/index.js
- packages/eslint-plugin-lit-a11y/lib/rules/no-invalid-change-handler.js
Fixes #2218
1. Deprecate no-invalid-change-handler lint rule
2. Turn rule off in recommended config
3. Update docs (adapted from eslint-plugin-jsx-a11y [docs](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-onchange.md))
> fix(eslint-plugin-lit-a11y): deprecate no-invalid-change-handler

- .changeset/short-lies-burn.md
- packages/scoped-elements/src/ScopedElementsMixin.js
- packages/scoped-elements/src/types.d.ts
- packages/scoped-elements/test-web/ScopedElementsMixin.test.js
1. Adjust the renderBefore node so that any styles in Lit content render before adoptedStyleSheets
fixes #2230
> fix(scoped-elements): adjust the renderBefore node

- .changeset/proud-foxes-kick.md
- packages/scoped-elements/src/ScopedElementsMixin.js
1. Use `SVGtemplateResult` in addition to `TemplateResult` transforming the templates, which allows using SVG templates with scoped elements.
Fixes #2112
> fix(scoped-elements): allows the use of svg templates

- docs/_data/componentLibraries.js
- docs/docs/development/generator.md
1. add "extending" docs to [generator page](https://deploy-preview-2270--open-wc-org.netlify.app/docs/development/generator/)
This is ahead of removing those docs from the create README
> docs: add "extending" docs to generator page

- docs/guides/developing-components/publishing.md
1. Fix a link typo in the Additional Reading section of "Publishing"
> docs(publishing): fix link in Additional Reading

- .changeset/fluffy-beds-pump.md
- packages/chai-a11y-axe/package.json
- packages/eslint-plugin-lit-a11y/lib/rules/role-has-required-aria-attrs.js
- packages/eslint-plugin-lit-a11y/package.json
- packages/eslint-plugin-lit-a11y/tests/lib/rules/autocomplete-valid.js
- packages/eslint-plugin-lit-a11y/tests/lib/rules/role-has-required-aria-attrs.js
- packages/semantic-dom-diff/test-web/__snapshots__/chai-dom-equals-snapshots.test.snap.js
- packages/testing/test-web/chai-a11y-axe.test.js
- yarn.lock
1. updated `axe-core` to get the freshest and hottest a11y rules
2. corrected `RoleHasRequiredAriaAttrsRule` to test for all required attributes but not to fail when there are more attributes beyond that list on the element.
> fix: use latest axe-core and allow not required attributes in role testing

- .changeset/tame-seals-listen.md
- packages/chai-a11y-axe/package.json
1. `chai-a11y-axe` got a 400 error that jacked up the publication on the last pre-release, I've manually bumped the number to see if we can get changesets to see this bump.
> fix: override bad publication

- docs/guides/tools/web-component-devtools.md
The docs that were in the previous PR creating the page were a bit deprecated after configuring the WCDT to use the CEM analyzer.
I've modified this page to reflect the changes to the more up to date ones. I've also updated the youtube link to a more up to date version video showcasing the features
> Update web component devtools docs

- .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE/pull_request_template.md
- .github/workflows/lint.yml
- README.md
1. add an action which
- any time a PR *REVIEW COMMENT* is created or edited
- IFF the comment contains the string `CI format please`
- run `yarn format:prettier && git add . && git commit && git push`
2. add a PR template which contains a note to reviewers 
- Do we want a different magic string, or to create an action with bash or JS or something to parse the comment?
- Would it be better to get a list of changed files and add them only? how? does prettier make that easy? (a cursory check of their docs didn't turn up much)
> chore: add format action for PR reviews

- .changeset/pink-queens-jump.md
- packages/testing-helpers/src/litFixture.js
1. Take scoped registries out of the static module graph.
fixes #2301
> Import scoped registries code dynamically.

- docs/docs/testing/helpers.md
1. Corrected the link to OpenWC Testing documentation.
> docs: update broken link to main testing page

- .changeset/wicked-maps-press.md
- packages/testing-helpers/src/helpers.js
By changing the declared signature of `waitUntil`, it will be possible call it in TypeScript without explicitly coercing the value to a boolean
> fix: relax waitUntil (fixes #2361)

- docs/_data/componentLibraries.js
1. Fixed the Material Design Components URL as the old one would point to a 404
> fix material design components url

- .changeset/shaggy-pigs-applaud.md
- docs/_data/componentLibraries.js
- packages/storybook-addon-markdown-docs/src/mdjsToMd.js
1. set sanitize to false (which was the default before but changed) => that should not be an issue as it's "revalidated" by storybooks mdx anyways
closes https://github.com/open-wc/open-wc/issues/2393
> fix(sb-md-docs): user provided code blocks should remain in final output

- .changeset/hot-pets-applaud.md
- packages/testing-helpers/src/helpers.js
- packages/testing-helpers/src/types.d.ts
Currently `oneEvent` is documented to always return `Promise<CustomEvent>`, but there is no reason it has to be `CustomEvent`. 
We can add a generic type param `TEvent`, constrained to `Event` to make this function more flexible. The default type is `CustomEvent` for backward compatibility
> Make `oneEvent` generic

- .github/workflows/canary.yml
1. Add a canary release workflow.
Looking to support test release cycles for #2399 and #2407 in hopes of clearing up some of the dependency vulnerabilities.
> build: add canary publish workflow

- .changeset/chilly-dragons-end.md
- package.json
- packages/testing-helpers/src/scopedElementsWrapper.js
- packages/testing-helpers/src/stringFixture.js
- yarn.lock
1. Ensure that `lit-html@2.0` is the preferred version so that it can be depended on via bare module specifiers in types.
> Force lit-html dependency tree for correct types construction

- .changeset/tame-queens-divide.md
- packages/lit-helpers/index.d.ts
1. Removed references to already removed d.ts files. This caused compilation issues when using it in a typescript enabled project.
> fix(lit-helpers): Removed references to removed type definitions

- .changeset/tall-stingrays-roll.md
- packages/scoped-elements/src/types.d.ts
1. Update `ScopedElementsMixin` type info to include `createScopedElement`
> fix(scoped-elements): update mixin type info to include createScopedElement

- package.json
- packages/testing/package.json
- yarn.lock
1. @esm-bundle/chai has an issue if I use vite/vitest for web component testing.  The hot fix version in @esm-bundle/chai has those deps fixed.  
Also, created a repo that reproduces the failure here, https://github.com/ianhuezo/vitest-failing-imports/tree/main/
> fix(deps): Fix deps issues with @esm-bundle/chai

- .changeset/purple-dolphins-compete.md
- packages/semantic-dom-diff/package.json
1. bump dependencies in `semantic-dom-diff`
In monorepos, prevents
>  SyntaxError: The requested module './../../../node_modules/@web/test-runner-commands/browser/commands.mjs' does not provide an export named 'sendMouse' (at pfe-cta.spec.ts:6:1)
> chore(semantic-dom-diff): update dependencies

- .changeset/hip-plants-change.md
- package.json
- packages/testing/package.json
- yarn.lock
1. Upgraded playwright to support macOS 12+
The previous installed version of Playwright (v1.10.0) did not support macOS 12+
as described in this github issue: https://github.com/microsoft/playwright/issues/7555
This was causing the yarn install command to fail for contributors on macOS 12+.
2. Upgraded chai-dom and its types
Resolves https://github.com/open-wc/open-wc/issues/2447
> Upgrade chai-dom and its types

- .changeset/sour-ants-relax.md
- package.json
- packages/eslint-config/package.json
- yarn.lock
1. Move `eslint` to the peerDependencies
2. Allow all major versions higher than `7.6.0`
ESLint was already marked in the docs as a "required" dependency to be installed when using the eslint-config package.
> breaking(eslint-config): move eslint to a peer to let users decide the major version

- .github/workflows/release.yml
1. Update the version of changesets/action that we consume.
> chore: use latest changesets/action for release workflows

- .changeset/few-mayflies-wave.md
- .changeset/lazy-teachers-study.md
- packages/testing-helpers/package.json
- packages/testing/package.json
Fixes missing type info when used with `node16` module resolution.
> Add types export to testing & testing-helpers

- .changeset/dirty-socks-leave.md
- package.json
- packages/eslint-config/package.json
- packages/eslint-plugin-lit-a11y/package.json
- packages/eslint-plugin-lit-a11y/tests/lib/rules/role-has-required-aria-attrs.js
- yarn.lock
1. Update `aria-query` dependency
2. Update tests for `role="switch"` to match w3 reqs (Closes #2506)
@a-kosanovic please confirm that the test case changes are correct. if they are, then there is a problem in upstream aria-query
> fix(eslint-plugin-lit-a11y): bump aria-query to v5, fix switch role rules

- .changeset/six-pears-hunt.md
- package.json
- packages/eslint-config/package.json
- yarn.lock
1. Upgraded `eslint-plugin-no-only-tests` to `3.1.0` - the only breaking change in v3 is [suite small](https://github.com/levibuzolic/eslint-plugin-no-only-tests/pull/35).
> feat(eslint-config): bump eslint-plugin-no-only-tests to v3

- .changeset/perfect-months-do.md
- package.json
- packages/eslint-config/package.json
- yarn.lock
1. Upgraded `eslint-plugin-html` to `7.1.0` (the only breaking change in v7 is that [Node 10 support is dropped](https://github.com/BenoitZugmeyer/eslint-plugin-html/blob/main/CHANGELOG.md)).
> feat(eslint-config): bump eslint-plugin-html to 7.1.0

- docs/docs/development/scoped-elements.md
Remove `@next` specifier from scoped-elements installation instructions, the latest release is no longer tagged `next`.
> Fix installation instructions for scoped-elements

- docs/guides/tools/linting-and-formatting.md
1. Remove `gid add` because it isn't necessary anymore. See lint-staged [v10 changelog](https://github.com/okonet/lint-staged#v10)
2. Change the husky example to use a command to create the desired hook
> Update lint-staged and husky examples

- .changeset/three-dogs-rhyme.md
- packages/chai-a11y-axe/chai-a11y-axe-plugin.d.ts
- packages/semantic-dom-diff/chai-dom-diff-plugin.d.ts
1. Changed return type of Equal from `Assertion` to `Promise<Assertion>`
2. Changed type `any` to `unknown`, which is preferred in TypeScript
Without this change, `tsserver`  gives the following warning:
`[tsserver 80007] [I] 'await' has no effect on the type of this expression.`  
Yet examples show `await`ing the assertions and the assertions must be awaited to work (in some cases).
> Change return type from Assertion to Promise<Assertion>

- .changeset/poor-days-cross.md
- docs/docs/testing/helpers.md
- packages/testing-helpers/index.js
- packages/testing-helpers/src/helpers.js
- packages/testing-helpers/src/types.d.ts
- packages/testing-helpers/test-web/helpers.test.js
Per this thread on slack: https://lit-and-friends.slack.com/archives/C0S7J1E86/p1646949557548319
1. added a new event helper function `oneDefaultPreventedEvent` so that events with a default that need to be prevented like form submits or anchor click events can be listened for without causing test issues
2. updated docs and imports
> feat(testing): add oneDefaultPreventedEvent function

- docs/docs/development/lit-helpers.md
typo fix - `ReadOnlyPropertiesMixin` provides a way for ????? based on `LitElement`  was missing the word "components"
1. added the word "components" to correct the sentence
> docs: update lit-helpers.md

- .changeset/shaggy-geckos-smash.md
- packages/scoped-elements/src/ScopedElementsMixin.js
- packages/scoped-elements/test-web/ScopedElementsMixinWithPolyfill.test.js
- packages/scoped-elements/test-web/runScopedElementsMixinSuite.js
In v1, the ScopedElementsMixin would add a random ID to your custom elements, like for example: `<ing-feat-foo-43539>` as the scoping mechanism to avoid duplicate custom elements being defined, which results in runtime errors. In @open-wc/scoped-elements v2, the ScopedElementsMixin has been aligned more closely with the Scoped Custom Element Registries proposal, which uses a CustomElementRegistry as the scoping mechanism, so we no longer have to add a random ID to the custom elements.
ScopedElementsMixin v1 provided a getScopedTagName method, to easily get the generated tagName for a given element, for example:
```js
this.getScopedTagName('ing-feat-foo'); // 'ing-feat-foo-43439'
```
This method has been deprecated in @open-wc/scoped-elements v2 (and frankly, should have just been removed …
> fix: getScopedTagName bug

- .changeset/mighty-cherries-tap.md
- packages/building-rollup/package.json
- packages/building-rollup/src/createBasicConfig.js
- yarn.lock
`rollup-plugin-terser` has been deprecated in favor of `@rollup/plugin-terser`
> Replace `rollup-plugin-terser` with `@rollup/plugin-terser`

- .changeset/quick-mirrors-flow.md
- packages/building-rollup/package.json
- yarn.lock
Fixes https://github.com/open-wc/open-wc/issues/2701
1. Bump `rollup-plugin-workbox` to `v8`, which includes the fix to the terser plugin import (https://github.com/modernweb-dev/web/pull/2265 in [`rollup-plugin-workbox` 8.0.0](https://github.com/modernweb-dev/web/releases/tag/rollup-plugin-workbox%408.0.0))
From what I can tell, no code changes are needed because `injectManifest` is not used.
> fix(building-rollup): fix rollup-plugin-terser error

- docs/_data/componentLibraries.js
1. Changed the link to material web library
2. Changed the name to the new branding (Material web (MWC))
> update material web links and info

- .changeset/blue-ladybugs-bathe.md
- packages/scoped-elements/src/ScopedElementsMixin.js
- packages/scoped-elements/src/types.d.ts
1. Backport passing the scoped custom element registry via the `registry` option in addition to the `customElement` option to account for the change in the specification
> fix: backport forward compatibility with registry property

- .changeset/proud-deers-study.md
- .changeset/rude-walls-divide.md
- package.json
- packages/eslint-config/package.json
- packages/eslint-plugin-lit-a11y/package.json
- packages/scoped-elements/package.json
- packages/testing-helpers/package.json
- tsconfig.browser-base.json
- yarn.lock
1. Split all versions of `lit` dependencies for consumption of ^2 || ^3.
> Use split versions for all lit dependencies

- .changeset/grumpy-owls-camp.md
- packages/testing-helpers/package.json
- packages/testing-helpers/src/fixture-no-side-effect.js
- packages/testing-helpers/src/helpers.js
- packages/testing-helpers/src/litFixture.js
- packages/testing-helpers/src/scopedElementsWrapper.js
- packages/testing-helpers/tsconfig.json
- packages/testing-helpers/tsconfig.override.json
- yarn.lock
chore: update @open-wc/scoped-elements to v3
If you're using a fixture like so with scoped elements:
```ts
await fixture(html`...`, { scopedElements: ... });
```
You're gonna have to load the [@webcomponents/scoped-custom-element-registry](https://www.npmjs.com/package/@webcomponents/scoped-custom-element-registry) polyfill yourself first.
> chore(testing-helpers): update @open-wc/scoped-elements to v3

- docs/_data/componentLibraries.js
Hi, I'd like to introduce the Porsche Design System component library to the _Community: Component Libraries_ list under https://open-wc.org/guides/community/component-libraries/ which is based on Web Components.
> Porsche Design System provides developers with versioned packages of Web components, Angular components, React components and Vue components to build clean and high-quality frontends that innately come with the latest design definitions.
https://designsystem.porsche.com/
> Add Porsche Design System to componentLibraries

- .changeset/sweet-clocks-share.md
- docs/_data/componentLibraries.js
- packages/scoped-elements/html-element.js
- packages/scoped-elements/package.json
I think in https://github.com/open-wc/open-wc/pull/2224 we just removed `sideEffects` instead of setting it to `false` which I believe is the correct value as `dedupeMixin` is side-effect free and by moving some top-level code into the `ScopedElementsMixin` we can make that side-effect free as well.
> Scoped elements no side effects

- .changeset/moody-panthers-visit.md
- packages/testing-helpers/src/types.d.ts
1. Corrected the type declaration for `oneEvent` and `oneDefaultPreventedEvent` functions
fixes #2746
> fix(testing-helpers): correct type declaration for `oneEvent`

- .changeset/pink-squids-attend.md
- packages/eslint-plugin-lit-a11y/lib/utils/isCustomElement.js
- packages/eslint-plugin-lit-a11y/tests/lib/rules/click-events-have-key-events.js
The existing regex would prevent valid custom elements from being detected appropriately.
The [spec](https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name) indicates that a valid custom name must start with a lowercase a-z but the next word between that character and the hyphen doesn't necessarily need to be present as the `+` in the existing regex indicates.
This makes it so custom elements such as `<d-button>` or `<q-tooltip>` are detected as such.
> fix(eslint-plugin-lit-a11y) fix improper regex

- docs/docs/linting/eslint-plugin-lit-a11y/overview.md
- docs/docs/linting/eslint-plugin-lit-a11y/rules/list.md
Address https://github.com/open-wc/open-wc/issues/2796 via the following changes
1. Add copy of list.md to ``docs/docs/linting/eslint-plugin-lit-a11y/rules`` from the package rules
2. Add a reference to this newly copied file in ``docs/docs/linting/eslint-plugin-lit-a11y/overview.md``
Side note: I noticed that the list of rules within the package && this docs folder are not aligned for other rules as well - is maintaining this documentation in two locations like this adding unnecessary maintenance cost? Just an observation as an outsider.
> Add lit-a11y/list to eslint-plugin-lit-a11y docs/../overview.md

- packages/semantic-dom-diff/chai-dom-diff-plugin.d.ts
Add missed .js extension to import. This matches the convention in
packages/semantic-dom-diff/index.d.ts and fixes the typing error:
```
node_modules/@open-wc/semantic-dom-diff/chai-dom-diff-plugin.d.ts:3:29 - error TS2835: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './get-diffable-html.js'?
3 import { DiffOptions } from './get-diffable-html';
```
> fix(semantic-dom-diff): add missed extension to import

- docs/docs/development/lit-helpers.md
Update installation command. Using @next installs version 0.4.0-next.1 and that version does not include the spread directives while this page implies that it does. Using without @next installs version 0.7.0 which does include the spread directives as the documentation describes.
1. Updated the documentation for the lit-helpers page to show the correct installation command, the one currently showing is outdated.
> Update lit-helpers.md to install correct package version
