open-wc/open-wc

packages/generator-open-wc/generators/lint-eslint/templates/_package.json, packages/generator-open-wc/generators/lint-eslint/templates/static/.eslintignore, packages/generator-open-wc/generators/publish-storybook/templates/static/stories/index.stories.js, packages/generator-open-wc/generators/testing-bare/templates/_package.json, packages/generator-open-wc/generators/testing-bare/templates/my-el.test.js, packages/generator-open-wc/generators/testing-bare/templates/static/test/index.html, packages/generator-open-wc/generators/testing-bare/templates/static/test/index.js, packages/generator-open-wc/generators/testing-karma/templates/static/karma.conf.js, packages/generator-open-wc/generators/testing-karma/templates/static/test/index.karma.js
update generators to reflect latest changes
=> fix(generator-open-wc): update testing and linting

packages/webpack/README.md, packages/webpack/loaders/import-meta-url-loader.js, packages/webpack/test/caseA/return.js, packages/webpack/test/import-meta-url-loader.test.js
is ready now :)
closes: https://github.com/open-wc/open-wc/issues/62
=> fix(webpack): support import.meta; new URL(./, import.meta.url)

docs/.vuepress/config.js, docs/recommendations/linting-prettier.md, packages/prettier-config/LICENSE, packages/prettier-config/README.md, packages/prettier-config/package.json, packages/prettier-config/prettier.config.js
=> feat(prettier-config): add prettier and eslint-config-prettier

packages/testing-karma/create-karma-config.js, packages/testing-karma/package.json
closes: https://github.com/open-wc/open-wc/issues/86, https://github.com/open-wc/open-wc/issues/83
=> feat: use karma-webpack#5.0.0-alpha.1 for proper webcomponents support

packages/testing-helpers/helpers.js
Fixes https://github.com/open-wc/open-wc/issues/75
=> chore: remove async keyword

docs/recommendations/ide.md
Unnecessary theme setting override
=> Remove Theme

packages/testing-helpers/README.md
=> docs(testing-helpers): fix fixture call on samples

packages/polyfills-loader/README.md, packages/polyfills-loader/package.json, packages/polyfills-loader/polyfills-loader.js, packages/polyfills-loader/src/webcomponents-all.js, packages/polyfills-loader/src/webcomponents-sd-ce.js
Need to test it after webpack is merged
=> feat(polyfills-loader): use only es modules in polyfills loader

packages/dev-server/LICENSE, packages/dev-server/README.md, packages/dev-server/demo/index.html, packages/dev-server/demo/module-a.js, packages/dev-server/demo/module-b.js, packages/dev-server/dev-server.js, packages/dev-server/package.json
No global docs changes, I want to do that as a bigger MR of updating the building/development docs.
=> feat(dev-server): added dev server

packages/testing/index.js
=> fix(testing): missing nextFrame export

docs/.vuepress/config.js, docs/about/rationales.md
- I think something around this should be open-wc's vision/goal
- this is a starting point for dicussion
- this is by fare not final
=> feel free to do suggestions or add commits 🤗 
and pls if someone can improve my wording that would be awesome 😊
=> docs: add rationals for what we recommend

packages/testing-helpers/fixture-no-side-effect.js, packages/testing-helpers/package.json, packages/testing-helpers/test/fixture.test.js
=> [testing-helpers] Use asynchronous fixtures 

packages/testing-helpers/README.md
=> docs(testing-helpers): mention lit-html peer dependency

packages/building-webpack/package.json, packages/chai-dom-equals/package.json, packages/eslint-config/package.json, packages/generator-open-wc/package.json, packages/owc-dev-server/package.json, packages/polyfills-loader/package.json, packages/prettier-config/package.json, packages/semantic-dom-diff/package.json, packages/storybook/package.json, packages/testing-helpers/package.json, packages/testing-karma-bs/package.json, packages/testing-karma/package.json, packages/testing-wallaby/package.json, packages/testing/package.json, packages/webpack-import-meta-loader/package.json, packages/webpack/package.json
https://github.com/open-wc/open-wc/issues/224
=> fix: update package repository fields

packages/eslint-config/index.js
=> Allow config files to depend on devDependencies.

README.md, docs/.vuepress/config.js, docs/about/blog.md, docs/about/contact.md
=> chore: add blog section and twitter to contact

packages/eslint-config/README.md, packages/eslint-config/index.js, packages/eslint-config/package.json
- Adds docs linking to the eslint-config file (Fixes #235)
- Adds `eslint-plugin-wc` (Fixes #256)
- I'm unsure how `require.resolve` works with the plugin config
- Removes `bower_components`
/cc @daKmoR
=> update linter and docs

packages/testing-karma/README.md, packages/testing-karma/default-settings.js, packages/testing-karma/package.json
includes https://github.com/open-wc/open-wc/pull/255 as well
=> fix(testing-karma): replace deprecated import meta url loader

packages/create/package.json, packages/create/src/Generator.js, packages/create/src/core.js, packages/create/src/generators/app/index.js, packages/create/src/generators/testing/index.js, packages/create/src/helpers.js
Adds options to the generator cli
=> feat: add cli options

packages/create/src/generators/building-rollup/index.js, packages/create/src/generators/building-rollup/templates/_package.json, packages/create/src/generators/building-rollup/templates/static/rollup.config.js, packages/create/src/generators/building-rollup/templates/static/src/index.html
=> feat(create): building-rollup generator

packages/building-rollup/plugins/rollup-plugin-modern-web/rollup-plugin-modern-web.js
See https://github.com/open-wc/open-wc/issues/283#issuecomment-474382583
=> fix(building-rollup): fix path to dynamic-import-polyfill.js

packages/create/package.json, packages/create/src/create.js
=> feat: add version detection

CONTRIBUTING.md, packages/create/src/Generator.js, packages/create/src/core.js
fixes https://github.com/open-wc/open-wc/issues/284
It also allows the user to select the dependency manager.
Note: There is one problem where the prompt is fired twice, once before installing dependencies, and then at the end it prompts the user again. I am not sure why this is so perhaps one of you guys can look into that, I can't really figure it out.
=> [create] Fix bug with install deps

packages/create/src/core.js
fixes https://github.com/open-wc/open-wc/issues/324
Checked on Windows 10, MacOS Mojave, Linux Ubuntu 16.04.6 LTS, all works now 🎉
=> fix(create): fix generator install deps for Windows

docs/linting/linting-types.md
Fix the .js extension to .json so it matches the actual source file
=> docs: fix file extension

packages/semantic-dom-diff/package.json
Fixes https://github.com/open-wc/open-wc/issues/328
=> fix(semantic-dom-diff): remove postinstall

docs/faq/README.md, docs/faq/unit-testing-custom-events.md, docs/faq/unit-testing-init-error.md
suggested fix for
https://github.com/open-wc/open-wc/issues/228
=> docs: add checking for init errors to FAQ

packages/create/src/core.js, packages/create/src/generators/building-webpack/templates/_package.json
closes https://github.com/open-wc/open-wc/issues/341
=>  fix(create): handle windows file pathes as well

packages/building-webpack/src/modern-web-webpack-plugin.js
closes https://github.com/open-wc/open-wc/issues/342
nodes `path.join` uses system separators so on windows it will create urls like `foo\bar.js`... that maybe still works for browser if they are nice and accept/change them... but Terser just says `\b` is not a valid escape thing and breaks...
=> now we force `/` even on windows
=> fix(building-webpack): support windows file pathes as well

packages/testing-karma/default-config.js
closes https://github.com/open-wc/open-wc/issues/345
=> fix(testing-karma): resolve chrome launcher

packages/building-webpack/modern-and-legacy-config.js, packages/building-webpack/modern-web-webpack-plugin.js
- Make webpack plugin public so that it can be used without the default config
- Correctly reference options inside webpack plugin
=> feat(building-webpack): make custom webpack plugin public

docs/faq/component-libraries.md
=> fix:(docs) Copy edit.

packages/building-webpack/demo/js/demo-app.js, packages/building-webpack/demo/js/demo-component.js, packages/building-webpack/modern-and-legacy-config.js, packages/building-webpack/modern-config.js, packages/building-webpack/modern-web-webpack-plugin.js
Fixes https://github.com/open-wc/open-wc/issues/372
=> multiple webpack fixes

packages/create/src/Generator.js, packages/create/src/core.js, packages/create/src/generators/app/index.js, packages/create/test/core.test.js
=> feat(create): show tree of files to create

docs/linting/README.md
=> docs: fix setup step in linting section

packages/building-webpack/README.md
closes https://github.com/open-wc/open-wc/issues/390
=> fix(building-webpack): correct manual install steps

packages/create/src/generators/starter-app/templates/static/src/index.html
fixes https://github.com/open-wc/open-wc/issues/400
=> fix(create): add index.html to starter-app generator

packages/webpack-import-meta-loader/test/webpack-import-meta-loader.test.js, packages/webpack-import-meta-loader/webpack-import-meta-loader.js
fixes https://github.com/open-wc/open-wc/issues/410
tested on windows/mac
=> fix(webpack-import-meta-loader): fix filepaths

packages/create/src/generators/building-webpack/templates/_package.json
Fixes https://github.com/open-wc/open-wc/issues/425
=> chore(create): add missing webpack dependency

packages/building-webpack/README.md
fixes https://github.com/open-wc/open-wc/issues/385
=> docs(building-webpack): add non standard syntax warning

docs/developing/ide.md
closes https://github.com/open-wc/open-wc/issues/414
=> docs: add lit-plugin ide extension

packages/create/src/generators/wc-lit-element/templates/static/demo/index.js
=> fix(create): use correct attribute name in demo (#463)

docs/faq/component-libraries.md
One more for the components list.
=> feat: add ink components

packages/karma-esm/src/forked-babel-plugin-bare-import-rewrite.js
Fixes https://github.com/open-wc/open-wc/issues/459
=> fix(karma-esm): correctly resolve symlinks

packages/webpack-import-meta-loader/src/to-browser-path.js, packages/webpack-import-meta-loader/test/to-browser-path.test.js, packages/webpack-import-meta-loader/webpack-import-meta-loader.js
Fixes https://github.com/open-wc/open-wc/issues/476
=> fix(webpack-import-meta-loader): rewrite all backslashes

packages/webpack-import-meta-loader/package.json
=> chore: made sure src files are published too

packages/testing-karma/CHANGELOG.md
Fixed the *BREAKING CHANGES* section under version 2.0.0
=> Fixed formatting on @open-wc/testing-karma CHANGELOG.md

packages/demoing-storybook/README.md
=> doc(demoing): fix typo on story file pattern

packages/polyfills-loader/package.json
problem found by @daKmoR when bugfixing unpkg imports [[codepen](https://codepen.io/daKmoR/pen/ydeaQQ)]
=> fix(polyfills-loader): patch unpkg resolution error by specifying 'module'

packages/building-rollup/README.md, packages/building-webpack/README.md, packages/create/src/generators/barebone-app/templates/_package.json, packages/create/src/generators/barebone-app/templates/static/index.html, packages/create/src/generators/building-rollup/templates/_package.json, packages/create/src/generators/building-rollup/templates/static/index.html, packages/create/src/generators/building-rollup/templates/static/rollup.config.js, packages/create/src/generators/building-webpack/templates/_package.json, packages/create/src/generators/building-webpack/templates/static/index.html, packages/create/src/generators/building-webpack/templates/static/webpack.config.js, packages/create/src/generators/starter-app/templates/_package.json, packages/create/src/generators/starter-app/templates/static/README.md, packages/create/src/generators/starter-app/templates/static/index.html, packages/create/src/generators/wc-lit-element/templates/_package.json
Closes https://github.com/open-wc/open-wc/issues/492
=> fix: align scripts and update create

packages/create/src/generators/wc-lit-element/templates/_package.json
Fixes https://github.com/open-wc/open-wc/issues/500
=> fix(create): set app-index in component demo

packages/create/README.md, packages/create/src/generators/app/index.js
Fixes https://github.com/open-wc/open-wc/issues/429
=> fix: improve clarity of init

packages/building-rollup/modern-and-legacy-config.js, packages/building-rollup/modern-config.js
Fixes https://github.com/open-wc/open-wc/issues/534
=> fix(building-rollup): use the correct dynamicImportFunction

packages/es-dev-server/package.json, packages/es-dev-server/src/babel-compiler.js, packages/es-dev-server/src/middleware/babel.js
- Certificates were missing from npm package
- Compile errors were handled, but the 'async task' wasn't removed on error
=> fix dev server certificates and clean up async task

packages/es-dev-server/README.md, packages/es-dev-server/src/middleware/compatibility.js, packages/es-dev-server/src/middleware/message-channel.js, packages/es-dev-server/src/server.js, packages/es-dev-server/test/middleware/compatibility.test.js, packages/es-dev-server/test/middleware/reload-browser.test.js
closes https://github.com/open-wc/open-wc/issues/548
=> feat(es-dev-server): don't require index.html for transform middleware

packages/es-dev-server/README.md, packages/es-dev-server/demo/typescript/.babelrc, packages/es-dev-server/demo/typescript/index.html, packages/es-dev-server/demo/typescript/module-a.ts, packages/es-dev-server/demo/typescript/module-b.ts, packages/es-dev-server/package.json, packages/es-dev-server/src/babel-compiler.js, packages/es-dev-server/src/command-line-args.js, packages/es-dev-server/src/constants.js, packages/es-dev-server/src/middleware/babel.js, packages/es-dev-server/test/middleware/babel.test.js, tsconfig.json, yarn.lock
- Add `--file-extensions` flag output to babel node resolve plugin
- Add docs on how to use typescript
- Improve 'advanced' usage readme
=> feat(es-dev-server): add typescript support

packages/building-utils/package.json
fixes https://github.com/open-wc/open-wc/issues/577
=> fix(building-utils): add missing dependencies

packages/es-dev-server/README.md, packages/es-dev-server/demo/index-rewrite/es-dev-server.config.js, packages/es-dev-server/demo/index-rewrite/index.html, packages/es-dev-server/demo/index-rewrite/module-a.js, packages/es-dev-server/demo/index-rewrite/module-b.js, packages/es-dev-server/demo/monorepo/index.html, packages/es-dev-server/demo/monorepo/module-a.js, packages/es-dev-server/demo/monorepo/module-b.js, packages/es-dev-server/package.json
Closes https://github.com/open-wc/open-wc/issues/578
=> docs(es-dev-server): add docs on project structure request rewrite

packages/create/src/generators/demoing-storybook/templates/static/.storybook/addons.js, packages/create/src/generators/demoing-storybook/templates/static/.storybook/config.js, packages/demoing-storybook/demo/.storybook/addons.js, packages/demoing-storybook/demo/.storybook/config.js, packages/demoing-storybook/package.json, yarn.lock
- update `@open-wc/demoing-storybook` to include the a11y addon
- include these additions in the config of `create/demoing-storybook`
=> feat(demoing-storybook): add a11y addon to package and generator

packages/testing-karma/package.json, yarn.lock
Fixes https://github.com/open-wc/open-wc/issues/604
=> fix(testing-karma): add missing mocha dependency

packages/create/src/generators/demoing-storybook/templates/_package.json, packages/create/src/generators/testing-karma/templates/_package.json, packages/create/src/generators/testing-karma/templates/static/karma.conf.js
A new version of `demoing-storybook` was made in a previous PR and this points the generator code to use it.
=> fix(create): update testing-karma and demoing-storybook dependencies

docs/about/README.md
fixes word for `interoperability`
=> update readme.md typo

packages/es-dev-server/src/utils/transform-index-html.js, packages/es-dev-server/test/fixtures/simple/no-modules.html, packages/es-dev-server/test/middleware/transform-index-html.test.js
Fixes https://github.com/open-wc/open-wc/issues/622
=> fix(es-dev-server): handle html files without any modules

packages/building-rollup/README.md, packages/building-rollup/index.js, packages/building-rollup/package.json, packages/building-webpack/README.md, packages/building-webpack/index.js, packages/building-webpack/package.json
- adds `main` to rollup
- add `main` to webpack
- **asks** for naming approval
TO DO:
=> #616 Update building tools with `main` entry point.

packages/building-utils/index-html/extract-resources.js, packages/building-utils/package.json, packages/building-utils/test/index-html/extract-resources.test.js, yarn.lock
fixes https://github.com/open-wc/open-wc/issues/625
Looking for some opinions on whether this is the approach we want to take with these kinds of scripts.
=> fix(building-utils): don't extract external resources

packages/create/src/generators/building-rollup/templates/_package.json, packages/create/src/generators/building-rollup/templates/static/rollup.config.js, packages/create/src/generators/building-webpack/templates/static/webpack.config.js
- update deps and config for rollup
- update config for webpack
I meant to get this into the last PR for this issue. Working on the right communication practices as I get up to speed on the repo.
=> #616 Finish entry point updates by updating generator

packages/building-utils/index-html/create-index-html.js, packages/building-utils/index-html/loader-script.js, packages/building-utils/index-html/utils.js, packages/building-utils/test/index-html/loader-script.test.js, packages/building-utils/test/index-html/snapshots/loader-script/absolute-file-path.js, packages/building-utils/test/index-html/snapshots/loader-script/upwards-file-path.js, packages/es-dev-server/src/utils/transform-index-html.js, packages/es-dev-server/test/fixtures/simple/index.html, packages/es-dev-server/test/snapshots/transform-index-html/simple-all.html, packages/es-dev-server/test/snapshots/transform-index-html/simple-esm.html, packages/es-dev-server/test/snapshots/transform-index-html/simple-modern.html, packages/es-dev-server/test/snapshots/transform-index-html/simple-none.html
Fixes https://github.com/open-wc/open-wc/issues/630
=> fix(es-dev-server): correctly handle absolute and upwards file paths

packages/es-dev-server/package.json, packages/karma-esm/package.json
Fixes https://github.com/open-wc/open-wc/issues/634
=> fix: remove @types/deepmerge dependency

packages/karma-esm/README.md
Adds comma to fix example syntax.
=> docs: Fix example syntax

packages/es-dev-server/package.json, yarn.lock
Fixes https://github.com/open-wc/open-wc/issues/763
=> fix(es-dev-server): pin lexer version

packages/es-dev-server/package.json, packages/es-dev-server/src/utils/resolve-module-imports.js, yarn.lock
Update to the latest version of es-module-lexer
=> feat(es-dev-server): update es-module-lexer

packages/es-dev-server/package.json, yarn.lock
Fixes https://github.com/open-wc/open-wc/issues/778
=> fix(es-dev-server): pin lexer to 0.3.9

packages/building-utils/package.json, packages/es-dev-server/test/snapshots/transform-index-html/import-map-all.html, packages/es-dev-server/test/snapshots/transform-index-html/import-map-esm.html, packages/es-dev-server/test/snapshots/transform-index-html/import-map-modern.html, packages/es-dev-server/test/snapshots/transform-index-html/inline-module-all.html, packages/es-dev-server/test/snapshots/transform-index-html/inline-module-esm.html, packages/es-dev-server/test/snapshots/transform-index-html/inline-module-modern.html, packages/es-dev-server/test/snapshots/transform-index-html/simple-all.html, packages/es-dev-server/test/snapshots/transform-index-html/simple-esm.html, packages/es-dev-server/test/snapshots/transform-index-html/simple-modern.html, yarn.lock
=> fix: ensure correct module load order on edge

packages/create/src/generators/app-lit-element/templates/_MyApp.js
If you wanted to try out the generated app before or after this was reviewed, here is the command I used to create the app that found the original bug:
`npm init @open-wc  --type scaffold --scaffoldType app --features building --buildingType rollup --scaffoldFilesFor building --tagName any-name --writeToDisk true --installDependencies yarn`
=> fix for issue 813

packages/building-rollup/modern-and-legacy-config.js, packages/building-rollup/modern-config.js, packages/building-rollup/package.json
Happy Hacktoberfest! 👻 
Generated hashes for the compiled build example: `demo-app-16131eff.js`.
=> feat(building-rollup): add hash to legacy and modern config

__snapshots__/component-a.md, packages/semantic-dom-diff/chai-dom-diff-plugin.d.ts, packages/semantic-dom-diff/chai-dom-diff.js, packages/semantic-dom-diff/test/chai-dom-equals-snapshots.test.js, packages/semantic-dom-diff/test/chai-dom-equals.test.js
Adds support for negating assertions.
Fixes #731
=> fix(semantic-dom-diff): support negate

karma.bs.conf.js, packages/create/src/generators/testing-karma-bs/templates/static/karma.bs.config.js, packages/testing-karma-bs/README.md, packages/testing-karma-bs/index.js, packages/testing-karma-bs/package.json
#714 
Added an `index.js` file as the main file of the package. It is exporting an object with the `bsSettings` function as a key.
=> Added package main index.js file at testing-karma-bs package

packages/webpack-import-meta-loader/webpack-import-meta-loader.js
=> fix(webpack-import-meta-loader): transform template literals to js

packages/building-rollup/modern-and-legacy-config.js, packages/building-rollup/modern-config.js
=> Fix allow Workbox disable

packages/building-utils/package.json, packages/building-webpack/package.json, packages/chai-a11y-axe/package.json, packages/demoing-storybook/package.json, packages/es-dev-server/package.json, packages/eslint-config/package.json, packages/karma-esm/package.json, packages/prettier-config/package.json, packages/rollup-plugin-index-html/package.json, packages/semantic-dom-diff/package.json, packages/testing-helpers/package.json, packages/testing-karma-bs/package.json, packages/testing-karma/package.json, packages/testing-wallaby/package.json, packages/testing/package.json, packages/webpack-import-meta-loader/package.json, packages/webpack-index-html-plugin/package.json
Package tags are added to every package.
=> fix: add package keywords

packages/building-utils/package.json, packages/create/package.json, packages/es-dev-server/package.json, packages/import-maps-generate/package.json, packages/import-maps-resolve/package.json, packages/rollup-plugin-index-html/package.json, packages/semantic-dom-diff/package.json, packages/testing-helpers/package.json, packages/testing-karma/package.json, packages/testing/package.json, packages/webpack-import-meta-loader/package.json, packages/webpack-index-html-plugin/package.json, yarn.lock
=> fix: align used mocha version

packages/karma-esm/src/esm-config.js
Fixes https://github.com/open-wc/open-wc/issues/837
=> feat(karma-esm): log 404 requests

.eslintrc.js, packages/eslint-config/index.js, packages/eslint-config/package.json
affects: @open-wc/eslint-config
=> feat(eslint-config): use eslint-plugin-no-only-tests

packages/es-dev-server/src/cli.js, packages/es-dev-server/src/start-server.js
Fixes https://github.com/open-wc/open-wc/issues/926
=> fix(es-dev-server): only exit process when used from cli

docs/faq/unit-testing-custom-events.md
=> docs: add simple example to event unit test guide

packages/eslint-config/index.js
Fixes https://github.com/open-wc/open-wc/issues/703
=> feat(eslint-config): allow for-of loops in eslint

packages/building-rollup/demo/js/rollup.modern.no-index.config.js, packages/building-rollup/modern-and-legacy-config.js, packages/building-rollup/modern-config.js, packages/building-rollup/package.json, packages/karma-esm/src/esm-config.js
fixes https://github.com/open-wc/open-wc/issues/961
=> [building-rollup] Fix/allow regular js

packages/codelabs/src/basics/lit-html.md
So, what's in this MR:
- fixed the checkbox issue with the codelab, we should not be using the checked attribute
- created a few more aside's for things that are not directly related
- adapted some code snippets to not give the full code every time, especially when the full code is in the next paragraph 🙈 
- some wordings got simplified
=> feat(codelabs): improve codelab 2

docs/about/blog.md
see https://github.com/open-wc/open-wc/issues/715#issuecomment-539239496
close #715
=> docs: add "shared behaviors best practices"

packages/es-dev-server/src/utils/compatibility-transform.js
=> feat(es-dev-server): don't do compat transform with custom config

packages/demoing-storybook/src/start/cli.js
Fixes https://github.com/open-wc/open-wc/issues/1025
=> fix(demoing-storybook): default root-dir to cwd

packages/demoing-storybook/README.md
@daKmoR the compile target docs aren't necessary anymore, right?
=> chore(demoing-storybook): improve docs

packages/es-dev-server/src/cli.js, packages/es-dev-server/src/command-line-args.js, packages/es-dev-server/src/config.js, packages/es-dev-server/src/create-middlewares.js, packages/es-dev-server/src/middleware/response-body-cache.js, packages/es-dev-server/src/utils/compatibility-transform.js, packages/es-dev-server/src/utils/user-agent-compat.js, packages/es-dev-server/src/utils/utils.js, packages/karma-esm/src/setup-es-dev-server.js
@Westbrook I hope this will help with debugging the tests, just add `debug: true` to the `esm` option in karma
=> feat(es-dev-server): add debug logging option

packages/create/src/generators/linting-eslint/templates/_package.json, packages/create/test/snapshots/fully-loaded-app/package.json
closes https://github.com/open-wc/open-wc/issues/1076
=> feat(create): update linting config

packages/demoing-storybook/src/start/readCommandLineArgs.js, packages/demoing-storybook/src/start/transformers/createMdxToJs.js, packages/es-dev-server/src/command-line-args.js
fixes https://github.com/open-wc/open-wc/issues/1102
=> Storybook fixes and improvements

docs/developing/types.md
=> Fix typo in types.md

packages/create/src/generators/app-lit-element/templates/_package.json, packages/demoing-storybook/MIGRATION.md, packages/demoing-storybook/package.json
closes https://github.com/open-wc/open-wc/issues/1103
=> fix(demoing-storybook): use " for stories glob to support windows

packages/codelabs/src/intermediate/lit-html.md
=> fix(codelabs): add read property to newsapp render

packages/building-rollup/modern-and-legacy-config.js, packages/building-rollup/modern-config.js, packages/building-rollup/package.json, yarn.lock
fixes https://github.com/open-wc/open-wc/issues/1095
=> feat(building-rollup): use new node-resolve plugin name

packages/demoing-storybook/src/start/cli.js
=> fix(demoing-storybook): remove rootDir prefexing on storiesPattern

packages/create/src/generators/wc-lit-element/templates/_package.json
https://github.com/open-wc/open-wc/pull/953 with conflicts resolved
=> fix(generate): align versions in package.json template

packages/testing-karma-bs/README.md
This extends documentation to include windows command and fixes issue #1190
=> update browserstack set up username + key docs

packages/demoing-storybook/src/build/build.js, packages/demoing-storybook/src/shared/createMdxToJsTransformer.js, packages/demoing-storybook/src/shared/getAssets.js, packages/demoing-storybook/src/start/cli.js, packages/demoing-storybook/src/start/middleware/createServeManagerMiddleware.js, packages/demoing-storybook/src/start/transformers/createMdxToJs.js
Serve storybook manager sourcemap, the preview sourcemap is fixed in the storybook prebuilt
=> fix(demoing-storybook): serve sourcemap

packages/testing/import-wrappers/chai-dom.js, packages/testing/import-wrappers/chai.d.ts, packages/testing/import-wrappers/chai.js, packages/testing/import-wrappers/sinon-chai.js, packages/testing/index.js, packages/testing/register-chai-plugins.js
fixes https://github.com/open-wc/open-wc/issues/1091
fixes https://github.com/open-wc/open-wc/issues/989
=> fix(testing): make testing work with webpack

packages/es-dev-server/src/command-line-args.js
fixes https://github.com/open-wc/open-wc/issues/1195
=> fix(es-dev-server): don't join current working directory twice

docs/faq/events.md
Expand on event documentation.
closes #895 
Please review the copy here for clarity and desired context. I've only just finished the first draft and will be reviewing it tomorrow or the next myself.
=> docs: expanded event documentation

packages/codelabs/src/intermediate/lit-html.md
The custom element is news-app, not todo-app.
=> Error in name of element

packages/testing-helpers/src/helpers.js
=> docs(testing-helpers): clarify oneEvent docs

docs/testing/README.md
=> chore(testing): fix url to semantic-dom-diff

packages/testing/README.md
Fixes issue: https://github.com/open-wc/open-wc/issues/954
=> docs: added missing await to testing README.md

packages/karma-esm/src/esm-config.js
Fixes https://github.com/open-wc/open-wc/issues/1297
=> fix(karma-esm): dont run coverage on debug, context and web_modules

packages/create/package.json, packages/es-dev-server/package.json, packages/import-maps-generate/package.json, packages/import-maps-resolve/package.json, yarn.lock
fixes https://github.com/open-wc/open-wc/issues/1304
=> fix(create): update broken @babel/cli

packages/polyfills-loader/src/create-polyfills-loader.js
Fixes https://github.com/open-wc/open-wc/issues/1306
=> fix(polyfills-loader): don't read user babel config

packages/es-dev-server/README.md
files-extensions to string/array
=> doc(es-dev-server): update files-extensions type

packages/building-rollup/modern-and-legacy-config.js, packages/building-rollup/modern-config.js, packages/building-webpack/modern-and-legacy-config.js, packages/building-webpack/modern-config.js
closes https://github.com/open-wc/open-wc/issues/1219
=> Feat/support web-modules for building rollup/webpack

.circleci/config.yml
This PR is a work in progress of a proof of concept of using CircleCI workflows to decrease build times.
=> ci: attempt to persist to workspace

packages/lit-helpers/package.json, packages/scoped-elements/package.json
Closes https://github.com/open-wc/open-wc/issues/1331
=> fix: add setting so webpack can apply tree shaking on it

docs/.vuepress/config.js, docs/guide/dedupe-mixin.md, package.json, packages/dedupe-mixin/LICENSE, packages/dedupe-mixin/README.md, packages/dedupe-mixin/demo-typed/no-dedupe/LoggingMixin.js, packages/dedupe-mixin/demo-typed/no-dedupe/index.html, packages/dedupe-mixin/demo-typed/no-dedupe/index.js, packages/dedupe-mixin/demo-typed/no-dedupe/rollup.config.js, packages/dedupe-mixin/demo-typed/with-dedupe/LoggingMixin.js, packages/dedupe-mixin/demo-typed/with-dedupe/index.html, packages/dedupe-mixin/demo-typed/with-dedupe/index.js, packages/dedupe-mixin/demo-typed/with-dedupe/rollup.config.js, packages/dedupe-mixin/index.d.ts, packages/dedupe-mixin/index.js, packages/dedupe-mixin/package.json, packages/dedupe-mixin/src/dedupeMixin.js, packages/dedupe-mixin/test/dedupeMixin.test.js, yarn.lock
- nice documentation ✅ anything missing?
- TODO: types - also how to test?
- do we need more tests?
=> feat: add package dedupe-mixin

README.md, docs/about/README.md, docs/about/contact.md
fixes https://github.com/open-wc/open-wc/issues/1309
=> docs: fix broken slack invite links

packages/eslint-config/index.js, packages/eslint-config/package.json, yarn.lock
=> fix(eslint-config): add support for optional chaining

docs/guide/component-libraries.md
So, I made these components that I think you should include... sound like a good idea?
=> docs: add Spectrum Web Components

packages/rollup-plugin-html/rollup-plugin-html.js, packages/rollup-plugin-html/src/extractModules.js, packages/rollup-plugin-html/test/fixtures/rollup-plugin-html/foo/foo.html, packages/rollup-plugin-html/test/fixtures/rollup-plugin-html/foo/foo.js, packages/rollup-plugin-html/test/rollup-plugin-html.test.js, packages/rollup-plugin-html/test/src/extractModules.test.js
Resolve imports in inline modules relative to the HTML page.
=> fix(rollup-plugin-html): resolve imports in inline modules

docs/faq/README.md, docs/testing/testing-sinon.md
closes https://github.com/open-wc/open-wc/issues/1425
=> docs: clarify sinon documentation

packages/rollup-plugin-polyfills-loader/README.md, packages/rollup-plugin-polyfills-loader/src/createPolyfillsLoaderConfig.js, packages/rollup-plugin-polyfills-loader/src/types.d.ts, packages/rollup-plugin-polyfills-loader/test/rollup-plugin-polyfills-loader.test.js, packages/rollup-plugin-polyfills-loader/test/snapshots/customize-filetype.html, packages/rollup-plugin-polyfills-loader/test/src/createPolyfillsLoaderConfig.test.js
In the new rollup config we need to be able to set the file type explicitly.
=> feat(rollup-plugin-polyfills-loader): allow setting file type explicitly

packages/scoped-elements/src/ScopedElementsMixin.js, packages/scoped-elements/src/registerElement.js, packages/scoped-elements/test/ScopedElementsMixin.test.js
=> fix(scoped-elements): define previously unused lazy scoped elements

packages/codelabs/src/basics/web-components.md
=> docs(codelabs): fix typo in step 6

packages/building-rollup/src/babel/rollup-plugin-bundled-babel-helpers.js
Fixes https://github.com/open-wc/open-wc/issues/1512
=> fix(building-rollup): add transitive babel helper dependencies

.circleci/config.yml
Remove windows tests from CI because we need to pay for it :(
=> chore: remove windows CI

docs/.vuepress/config.js, docs/deploying/README.md
Prep for a new "publishing" section that will relate to getting components up to NPM/webcomponents.org/PIKA as well as this information on getting components/apps onto a live site.
=> docs: update to "deploying" to reduce confusion

package.json, packages/semantic-dom-diff/README.md, packages/semantic-dom-diff/chai-dom-diff-plugin.d.ts, packages/semantic-dom-diff/chai-dom-diff.d.ts, packages/semantic-dom-diff/chai-dom-diff.js, packages/semantic-dom-diff/get-diffable-html.d.ts, packages/semantic-dom-diff/get-diffable-html.js, packages/semantic-dom-diff/package.json, packages/semantic-dom-diff/test/bdd-setup.d.ts, packages/semantic-dom-diff/test/bdd-setup.js, packages/semantic-dom-diff/test/chai-dom-equals.test.js, packages/storybook-addon-markdown-docs/package.json, packages/testing/package.json, tsconfig.json, yarn.lock
=> fix(semantic-dom-diff): allow assertion message

packages/karma-esm/package.json, packages/karma-esm/src/esm-config.js, packages/testing-karma/demo/karma.conf.js, packages/testing-karma/package.json, packages/testing-karma/src/create-default-config.js, packages/testing-karma/testing-karma.d.ts, yarn.lock
=> fix(testing-karma): export types

packages/building-rollup/src/createSpaConfig.js
* Update previous `legacy` to current `nomodule`
* Add `polyfills` to `globIgnores`
* Add `webmanifest` to `globPatterns`
=> Update the Service Worker default config

packages/testing-helpers/README.md
=> docs(testing-helpers): describe parentNode

packages/building-rollup/src/createBasicConfig.js, packages/demoing-storybook/src/build/rollup/createRollupConfig.js
=> fix(building-rollup): node resolve config is incorrect

docs/guide/component-libraries.md
Added the Kor library to the component libraries page.
=> docs: Added Kor library

packages/create/src/generators/common-repo/index.js, packages/create/src/generators/common-repo/templates/static/LICENSE, packages/create/test/snapshots/fully-loaded-app/LICENSE
chore: Updated year in LICENSE to `2020`.
=> chore(create): Update LICENSE year

packages/rollup-plugin-html/demo/mpa/pages/page-b.js
Small typo to familiarize myself with openwc process
=> fix(rollup-plugin-html): typo

packages/building-utils/package.json, packages/es-dev-server/package.json, packages/polyfills-loader/package.json, yarn.lock
Update to systemjs v6 which supports import maps by default.
=> feat(polyfills-loader): update to systemjs v6

docs/_includes/home.njk, docs/_includes/layout.njk, docs/_includes/partials/sidebar-script.njk
Move the script to manage the side nav into an include for use on the homepage and inner templates.
=> docs: add side nav script to home page

packages/es-dev-server/src/create-middlewares.ts, packages/es-dev-server/src/plugins/babelTransformPlugin.ts, packages/es-dev-server/src/plugins/fileExtensionsPlugin.ts, packages/es-dev-server/src/plugins/nodeResolvePlugin.ts, packages/es-dev-server/src/plugins/polyfillsLoaderPlugin.ts, packages/es-dev-server/src/plugins/resolveModuleImportsPlugin.ts, packages/es-dev-server/test/plugins/resolveModuleImportsPlugin.test.ts
Fixes https://github.com/open-wc/open-wc/issues/1636
=> fix(es-dev-server): don't rely on serverStart for built-in plugins

packages/es-dev-server/README.md
=> docs(es-dev-server): improve readme

docs/_includes/partials/sidebar-guide.njk, docs/codelabs/README.md, docs/developing/best-practices.md, docs/developing/code-examples.md, docs/developing/ide.md, docs/developing/lit-html.md, docs/developing/types.md, docs/guide/component-libraries.md, docs/publishing/index.md
Super drafty as yet, but wanted to share. Particularly let me know about really bad things or really good things. Much in the middle, I'll hopefully change on my own in the next couple of days, anyways. I definitely got tired in the second half, so be warned.
=> docs: add Publishing Web Components guide

packages/es-dev-server/src/Plugin.ts
=> fix(es-dev-server): really fix plugin types

docs/publishing/index.md
@web-padawan this is for you! And, I guess npm...
=> docs: follow npm brand guidelines

packages/create/src/generators/app-lit-element-ts/templates/_tsconfig.json, packages/create/src/generators/wc-lit-element-ts/templates/_tsconfig.json
fixes https://github.com/open-wc/open-wc/issues/1654
=> fix(create): use rootDir to maintain file structure

docs/deploying/README.md
Deployment to GitHub pages #1662
=> docs: deployment to github pages

packages/rollup-plugin-html/rollup-plugin-html.js, packages/rollup-plugin-html/test/fixtures/rollup-plugin-html/pure-index.html, packages/rollup-plugin-html/test/fixtures/rollup-plugin-html/pure-index2.html, packages/rollup-plugin-html/test/rollup-plugin-html.test.js
closes https://github.com/open-wc/open-wc/issues/1672
Requires https://github.com/open-wc/open-wc/pull/1671 to be merged before 😅  or we merge into it...
=> fix(rollup-plugin-html): allow pure html input

docs/guide/component-libraries.md
=> docs: add Zooplus Web Components

packages/es-dev-server/demo/syntax/index.html, packages/es-dev-server/src/middleware/plugin-transform.ts, packages/es-dev-server/src/utils/babel-transform.ts
Fixes https://github.com/open-wc/open-wc/issues/1687
=> fix(es-dev-server): handle transforming empty modules

packages/building-rollup/README.md, packages/building-rollup/demo/js/rollup.spa-js-input.config.js, packages/building-rollup/src/createSpaConfig.js, packages/building-rollup/src/types.d.ts, packages/building-rollup/src/utils.js
closes https://github.com/open-wc/open-wc/issues/1737
=> feat(building-rollup): allow customizing sw name

packages/building-rollup/src/createSpaConfig.js
fix for https://github.com/open-wc/open-wc/pull/1738#issuecomment-653427680
=> fix(building-rollup): fix workbox typeguard

docs/guide/component-libraries.md
Added [Shoelace](https://shoelace.style/) and fix abc ordering.
=> Add Shoelace; sort alphabetically

docs/README.md, docs/_includes/home.njk
Just noticed these outdated copyright notices.
=> chore: Update copyright

docs/building/README.md
Just fixing some typos. Hopefully not adding new ones 😁
=> docs(building): Fix typos

docs/guide/component-libraries.md
More component libraries more awesome!
=> docs: add https://iooxa.dev/ libraries

packages/building-rollup/README.md, packages/building-rollup/package.json, packages/building-rollup/src/createBasicConfig.js, yarn.lock
- rollup-plugin-babel to @rollup/plugin-babel
Fixes https://github.com/open-wc/open-wc/issues/1583
=> fix(building-rollup): update babel dependency

packages/karma-esm/package.json, packages/testing-karma/package.json, yarn.lock
Fixes https://github.com/open-wc/open-wc/issues/1517
=> chore: upgrade to karma 5.1.1

docs/linting/README.md
Added a small change to docs in response to #918 and formatted this time in response to #1767 ...oops
=> docs: update linting/prettier instruction

packages/building-rollup/package.json, packages/building-rollup/src/babel/babel-configs.js, packages/building-rollup/src/createBasicConfig.js, packages/building-utils/package.json, packages/building-webpack/package.json, packages/create/package.json, packages/create/test/snapshots/fully-loaded-app/package.json, packages/demoing-storybook/package.json, packages/es-dev-server/package.json, packages/import-maps-generate/package.json, packages/karma-esm/package.json, packages/polyfills-loader/package.json, packages/storybook-addon-markdown-docs/package.json, yarn.lock
Combine multiple updates
Fixes https://github.com/open-wc/open-wc/pull/1808 Fixes https://github.com/open-wc/open-wc/pull/1783
=> Building updates

packages/create/owc-app/package.json, packages/create/package.json, packages/create/src/generators/app-lit-element-ts/templates/_package.json, packages/create/src/generators/app-lit-element/templates/_package.json, packages/create/src/generators/building-rollup-ts/templates/_package.json, packages/create/src/generators/building-rollup/templates/_package.json, packages/create/src/generators/wc-lit-element-ts/templates/_package.json, packages/create/src/generators/wc-lit-element-ts/templates/static/README.md, packages/create/src/generators/wc-lit-element/templates/_package.json, packages/create/src/generators/wc-lit-element/templates/static/README.md, packages/create/test/snapshots/fully-loaded-app/package.json
Fix #1843 
Please let me know if there is any place missing.
Also, I see that this check `security/snyk (daKmoR) — 1 test has failed` is failing, not sure if I need to do something ?
Thanks !
=> feat(generators): update to use @web/dev-server

docs/_includes/partials/sidebar-guide.njk, docs/testing/README.md, docs/testing/karma-esm.md, docs/testing/testing-karma-bs.md, docs/testing/testing-karma.md, packages/karma-esm/README.md, packages/testing-helpers/README.md, packages/testing-karma-bs/README.md, packages/testing-karma/README.md, packages/testing-wallaby/README.md
This updates the documentation to recommend WTR over Karma.
=> docs: recommend WTR over karma

packages/create/src/generators/wc-lit-element-ts/templates/_package.json, packages/create/src/generators/wc-lit-element-ts/templates/_tsconfig.json
=> feat(create): add prepublish script to typescript wc generator

packages/eslint-plugin-lit-a11y/lib/rules/click-events-have-key-events.js, packages/eslint-plugin-lit-a11y/tests/lib/rules/click-events-have-key-events.js
Hi,
I believe this fix #1878 
Please let me know if you see anything missing or incorrect !
Thank you !
=> feat(eslint-plugin-lit-a11y): add click-events-have-key-events whitelist

packages/eslint-plugin-lit-a11y/docs/rules/scope.md, packages/eslint-plugin-lit-a11y/lib/rules/scope.js, packages/eslint-plugin-lit-a11y/package.json, packages/eslint-plugin-lit-a11y/tests/lib/rules/scope.js
Hi,
It should fix #1886.
As we talked in Slack, I have also added scope value validation (row, col, rowgroup and colgroup).
Please let me know if you see any issue.
Thanks
=> feat(eslint-plugin-lit-a11y): allow only valid scopes

packages/eslint-plugin-lit-a11y/lib/rules/alt-text.js
somehow we ended up importing this polyfill twice
=> chore(eslint-plugin-lit-a11y): remove dupe block

packages/eslint-plugin-lit-a11y/lib/rules/role-supports-aria-attr.js, packages/eslint-plugin-lit-a11y/tests/lib/rules/role-supports-aria-attr.js
fixes https://github.com/open-wc/open-wc/issues/1940
=> fix(eslint-plugin-lit-a11y): guard against placeholders

docs/_data/baseLibraries.js
1. Updated the list of base libraries based on https://webcomponents.dev/blog/all-the-ways-to-make-a-web-component/.
2. Corrected stencil NPM package
=> docs: add more libraries

.changeset/fluffy-students-jam.md, packages/scoped-elements/src/types.d.ts, packages/testing-helpers/package.json
1. Fix ScopedElementsMixin types
=> fix(scoped-elements): types

packages/demoing-storybook/README.md
=> docs: expand on "@open-wc/demoing-storybook" documentation

docs/docs/development/lit-helpers.md
1. I added a comma that was missing.
=> Add missing comma in lit-helpers.md

.changeset/good-tips-cheer.md, docs/blog/announcing-open-web-components/index.md, docs/docs/development/hot-module-replacement.md, docs/docs/linting/eslint-plugin-lit-a11y/overview.md, docs/docs/testing/helpers.md, docs/guides/knowledge/attributes-and-properties.md, packages/dev-server-hmr/demo/haunted/index.html, packages/dev-server-hmr/demo/haunted/server.config.mjs, packages/dev-server-hmr/demo/haunted/src/sharedStyles.js, packages/dev-server-hmr/demo/haunted/src/sharedTemplate.js, packages/dev-server-hmr/demo/haunted/src/todo-app.js, packages/dev-server-hmr/demo/haunted/src/todo-item.js, packages/dev-server-hmr/demo/haunted/src/todo-list.js, packages/dev-server-hmr/demo/lit-element/src/sharedTemplate.js, packages/dev-server-hmr/package.json, packages/dev-server-hmr/src/babel/babelPluginWcHmr.js, packages/dev-server-hmr/src/babel/customElementsDefine.js, packages/dev-server-hmr/src/babel/functions.js, packages/dev-server-hmr/src/babel/getImportedVariableNames.js, packages/dev-server-hmr/src/hmrPlugin.js, packages/dev-server-hmr/src/presets/haunted.js, packages/dev-server-hmr/src/utils.js, packages/dev-server-hmr/test-node/babel/customElements.test.js, packages/dev-server-hmr/test-node/babel/functions.test.js, packages/eslint-plugin-lit-a11y/README.md, packages/testing-helpers/README.md, yarn.lock
1. Added support for components created with functions:
```js
const MyComponentClass = component(MyComponent):
```
2. Started on support for haunted. See https://github.com/matthewp/haunted/issues/217
=> feat(dev-server-hmr): support function components

.changeset/silver-horses-divide.md, packages/dev-server-hmr/src/babel/babelPluginWcHmr.js, packages/dev-server-hmr/test-node/babel/decorators.test.js
Fixes https://github.com/open-wc/open-wc/issues/1999
=> fix(dev-server-hmr): handle multiple assigned variables

README.md
1. Added ING to "Supported By" section
We should also show it on open-wc.org, where should we add it? 🤔 @daKmoR @Westbrook
=> chore: add ING to supported by

docs/_assets/style.css, docs/_includes/home.njk, docs/index.md
=> chore: add supported by to website

README.md, docs/index.md
=> chore: remove ING from supports until approved by ING communications

README.md, docs/index.md
Reverts open-wc/open-wc#2010
This time we do have approvals and we can go again. Sorry for the mambo jumbo :)
=> Revert "chore: remove ING from supports until approved by ING communications"

.changeset/big-goats-sleep.md, packages/eslint-config/package.json
=> Update eslint-plugin-lit to ^1.3.0

.changeset/big-goats-sleep.md, .changeset/gentle-mangos-agree.md, docs/docs/development/hot-module-replacement.md, packages/dev-server-hmr/TODO.md, packages/dev-server-hmr/demo/haunted/server.config.mjs, packages/dev-server-hmr/demo/haunted/src/todo-list.js, packages/dev-server-hmr/demo/lit-element/src/SharedClass.js, packages/dev-server-hmr/demo/lit-element/src/todo-app.js, packages/dev-server-hmr/demo/lit-element/src/todo-list.js, packages/dev-server-hmr/demo/lit-element/src/todo-shared-a.js, packages/dev-server-hmr/demo/lit-element/src/todo-shared-b.js, packages/dev-server-hmr/demo/vanilla/src/BaseClass.js, packages/dev-server-hmr/src/babel/babelPluginWcHmr.js, packages/dev-server-hmr/src/babel/customElementsDefine.js, packages/dev-server-hmr/src/babel/decorators.js, packages/dev-server-hmr/src/babel/functions.js, packages/dev-server-hmr/src/babel/inject.js, packages/dev-server-hmr/src/babel/utils.js, packages/dev-server-hmr/src/hmrPlugin.js, packages/dev-server-hmr/src/index.js, packages/dev-server-hmr/src/presets/fastElement.js, packages/dev-server-hmr/src/presets/haunted.js, packages/dev-server-hmr/src/presets/litElement.js, packages/dev-server-hmr/src/utils.js, packages/dev-server-hmr/src/wcHmrRuntime.js, packages/dev-server-hmr/test-node/babel/base-class.test.js, packages/dev-server-hmr/test-node/babel/customElements.test.js, packages/dev-server-hmr/test-node/babel/decorators.test.js, packages/dev-server-hmr/test-node/babel/functions.test.js
1. Updated HMR implementation to be based on proxies, making HMR more transparent and covering a lot more cases.
2. Make newly constructed elements use the latest updated class.
3. Make HMR work for Haunted
=> feat(dev-server-hmr): implement HMR using proxies

.changeset/itchy-suns-film.md, packages/semantic-dom-diff/get-diffable-html.js, packages/semantic-dom-diff/src/utils.js, packages/semantic-dom-diff/test-web/chai-dom-equals.test.js, packages/semantic-dom-diff/test-web/get-diffable-html.test.js
1. Concatenates the sibling text nodes.
Fixes: https://github.com/open-wc/open-wc/issues/2017
=> fix(semantic-dom-diff): normalize adjacent textNodes

docs/_data/site.js, docs/blog/index.md, package.json, rocket.config.mjs, yarn.lock
1. Update to latest rocket
2. Now using presets instead of themes
=> chore: update to latest rocket packages

docs/404.md, docs/sitemap.njk, package.json, rocket.config.mjs, yarn.lock
1. Let the server handle 404s
2. add 404 page
3. add a sitemap
=> chore: let server handled 404s; add 404 page; add sitemap

docs/docs/demoing/storybook.md, docs/docs/testing/helpers.md, docs/guides/developing-components/publishing.md, docs/guides/index.md, docs/guides/knowledge/styling/styles-piercing-shadow-dom.md, package.json, packages/dev-server-hmr/package.json, rocket.config.mjs, yarn.lock
1. Make sure the option `emptyOutputDir: false,` is respected so codelabs exist when deploying
=> chore: do not clean outputDir to keep codelabs via using latest rocket

docs/_data/componentLibraries.js
1. Added [Crayons](https://crayons.freshworks.com/) to the component library list
=> docs: add Crayons to component libraries list

docs/index.11tydata.cjs, package.json, yarn.lock
1. Enables the capability to customize the social media image svg
2. Sets a nicer social media image for the home page
=> If someone with a little more skill then me in svg could improve it even more and also make the "default" one nicer that would be awesome
=> chore: nicer social media image for homepage

packages/storybook-addon-markdown-docs/package.json
Hey open-wc! We've created a catalog of Storybook addons and yours is included: https://storybook.js.org/addons/storybook-addon-markdown-docs
To make your addon more discoverable in the catalog, we've curated some of its metadata, and I've included those edits in this PR.
To learn more about the catalog metadata, check out our documentation: https://storybook.js.org/docs/react/addons/addon-catalog
=> Update Storybook addon metadata

.changeset/honest-rice-roll.md, packages/testing/index-no-side-effects.js
Fixes https://github.com/open-wc/open-wc/issues/2109
=> feat(testing): export waitUntil from index-no-side-effects

.changeset/breezy-camels-attend.md, packages/dev-server-hmr/package.json, yarn.lock
Fixes https://github.com/modernweb-dev/web/issues/1399
=> fix(dev-server-hmr): use correct babel dependency

CONTRIBUTING.md
I cleaned up and expanded the CONTRIBUTING instructions. I also filed modernweb-dev/web#1416 at Modern Web to make the CONTRIBUTING files match.
=> Clean up CONTRIBUTING and match modernweb-dev

.changeset/healthy-queens-prove.md, docs/docs/development/scoped-elements.md, packages/scoped-elements/src/ScopedElementsMixin.js, packages/scoped-elements/src/types.d.ts, packages/scoped-elements/test-web/ScopedElementsMixin.test.js
1. I modified `ScopedElementsMixin` to use one `CustomElementsRegistry` for each component class instead of for each component instance.
=> feat(scoped-elements): one registry for each component class

.changeset/breezy-camels-attend.md, .changeset/early-rockets-matter.md, .changeset/healthy-queens-prove.md, .changeset/modern-elephants-collect.md, .changeset/pre.json, docs/blog/updating-to-lit-2-0/index.md, docs/docs/development/hot-module-replacement.md, docs/docs/development/scoped-elements.md, packages/scoped-elements/demo/with-scope/index.html, packages/scoped-elements/package.json, packages/scoped-elements/src/ScopedElementsMixin.js, packages/scoped-elements/src/loadPolyfill.js, packages/scoped-elements/test-web/ScopedElementsMixin.test.js, web-test-runner.config.mjs
=> Release Lit 2 updates as prerelease

docs/404.md, docs/blog/index.md, docs/docs/development/scoped-elements.md, docs/index.md, docs/sitemap.njk, package.json, yarn.lock
1. Update rocket to latest version to fix for example the search overlay centering
=> chore: update rocket to latest version

docs/blog/updating-to-lit-2-0/index.md, docs/docs/development/scoped-elements.md, packages/eslint-plugin-lit-a11y/package.json
1. chore: finish and publish update to lit2 blog post
=> chore: finish and publish update to lit2 blog post

docs/blog/updating-to-lit-2-0/index.md
1. add migration help to blog post
=> chore: add migration help to blog post

docs/blog/testing-workflow-for-web-components/index.md
1. I removed an extra character so the blog post is displayed correctly, otherwise the whole second half of the blog post look like 1 big piece of code, which makes it very difficult to read.
=> Fix blog post to display correctly

docs/_data/componentLibraries.js
1. Update carbon-web-components repo link
=> Update carbon-web-components repo link

docs/_data/componentLibraries.js
=> Fix broken link

.changeset/chilly-terms-drive.md, package.json, packages/semantic-dom-diff/chai-dom-diff.js, packages/semantic-dom-diff/package.json, packages/semantic-dom-diff/src/utils.d.ts, packages/semantic-dom-diff/src/utils.js, packages/semantic-dom-diff/test-web/__snapshots__/chai-dom-equals-snapshots.test.snap.js, packages/semantic-dom-diff/test-web/chai-dom-equals-snapshots.test.js, web-test-runner.config.mjs, yarn.lock
Added snapshot testing with WTR
=> feat(semantic-dom-diff): support snapshot testing with WTR

.changeset/dry-bobcats-nail.md, packages/building-rollup/package.json, yarn.lock
Mirror of https://github.com/open-wc/open-wc/pull/2053 with conflicts resolved
=> feat(building-rollup): update to rollup-plugin-workbox v6

.github/workflows/verify-node.yml
1. Replace deprecated `microsoft/playwright-github-action`
=> Replace deprecated `microsoft/playwright-github-action`

docs/_data/componentLibraries.js
1. add [patternfly elements](https://patternflyelements.org/) to components libraries
=> docs: add PatternFly Elements to libraries

.github/workflows/release.yml, .github/workflows/verify-node.yml
1. Update to actions/setup-node@v2
2. Use the built-in cache
=> Update to actions/setup-node@v2 and use the built-in cache

packages/codelabs/src/intermediate/lit-html.md
1. Fixed a grammar error in the codelabs : lit-html & lit-element: intermediate introduction section.
This is my first open source PR :) was just trying to see how the process works. Its so cool! Thank you for open-wc!
=> grammar fix in codelabs

.changeset/plenty-bikes-wave.md, package.json, packages/semantic-dom-diff/chai-dom-diff.js, yarn.lock
1. Snapshot testing with WTR updated to not modify the snapshot files running the tests, which was causing race conditions when tests were run by several browsers.
=> fix(semantic-dom-diff): snapshot testing with WTR

.changeset/mighty-penguins-smile.md, packages/testing/package.json, yarn.lock
1. Remove unused dependency on `mocha` as the environment should bring it.
=> fix(testing): remove unused mocha dependency

.changeset/clever-falcons-obey.md, packages/lit-helpers/package.json, packages/scoped-elements/package.json, packages/scoped-elements/src/ScopedElementsMixin.js, packages/testing-helpers/package.json, yarn.lock
1. Fill cut over to `lit@2.0`.
=> Use lit@2.0

docs/guides/knowledge/events.md
=> doc(events): fix typo

docs/guides/knowledge/styling/styles-piercing-shadow-dom.md
fixes #2305
1. update the description of `all` css property
2. fix and update the code sample at https://webcomponents.dev/edit/NeHSCFaBjUkpe5ldUu1N/src/index.js
=> docs: css all initial

docs/blog/some-things-to-know-when-developing-with-lit/index.md
=> Fix blog post image references

.github/workflows/preview.yml, package.json, yarn.lock
1. Update Netlify CLI
2. Build and publish docs from Github Actions 🤞🏼 
3. Save money!
=> Publish to Netlify from CI

.github/workflows/preview.yml
Fix the preview URLs.
It doesn't work in some URLs like:
https://github.com/open-wc/open-wc/pull/2066#issuecomment-1005795429
Slugified branch name from:
https://github.com/adobe/spectrum-web-components/blob/main/.circleci/config.yml#L152-L154
=> Fix the preview URLs

docs/_data/componentLibraries.js
1. added Vonage's vivid web components library to the _componentLibraries_ list
=> chore(component libraries): add vivid

docs/discover/slack.md
Fix #2335 
1. Update #open-wc slack channel URL (please let me know if this is the correct URL)
2. Update Lit & Friends Slack URL
Please let me know if you have any question or need any other change.
Thanks !
=> docs: update lit and friends slack url

docs/_assets/style.css, docs/_assets/variables.css, package.json, yarn.lock
=> chore: update rocket to latest stable version

.changeset/polite-beds-shop.md, packages/testing-helpers/src/renderable.ts
=> fix: add a type for lit v1 renderable

docs/guides/knowledge/events.md
=> Typo fix (documentation)

.changeset/twelve-ligers-crash.md
1. Adding changeset for the recent PR, https://github.com/open-wc/open-wc/pull/2432
=> fix(testing): esm-bundle/chai version update

.changeset/sharp-falcons-type.md, packages/testing/package.json, yarn.lock
1. bump semantic-dom-diff in testing package
2. rebuild yarn.lock
=> chore(testing): bump semantic dom diff

docs/guides/developing-components/publishing.md
1. Fixed typo EcmaScrip to EcmaScript
=> Correct wrong spelling in publishing.md file

.changeset/thin-onions-run.md, packages/eslint-plugin-lit-a11y/lib/rules/role-supports-aria-attr.js, packages/eslint-plugin-lit-a11y/tests/lib/rules/role-supports-aria-attr.js
=> fix(eslint-plugin-lit-a11y): add missing valid role check in `role-supports-aria-attr` rule

.github/workflows/release.yml
=> chore: match Changeset usage to their own usage

package.json, yarn.lock
=> chore: use latest changeset CLI

.changeset/smart-baboons-count.md
=> fix version type

docs/_data/componentLibraries.js
1. add Nord Design System component library
=> Nord Design System component library

docs/_data/baseLibraries.js
1. Add FicusJS (https://www.ficusjs.org/) to the list of available base libraries
=> docs: add FicusJS to the list of base libraries

.changeset/fast-hairs-live.md, packages/scoped-elements/package.json
=> fix(scoped-elements): add type entrypoint

.changeset/eighty-llamas-repeat.md, package.json, packages/eslint-config/index.js, packages/eslint-config/package.json, yarn.lock
=> feat: update eslint-plugin-lit

.changeset/sweet-donuts-lie.md, packages/eslint-config/index.js, packages/eslint-config/package.json
=> feat(eslint-config): support import assertions

docs/_data/baseLibraries.js
1. Updated bay.js description in base library.
=> base lib update for bay.js

docs/_data/componentLibraries.js
1. Added [Duet Design System](https://www.duetds.com/)
=> added duet design system

.changeset/foo-bar-baz.md
=> ci: release new v

docs/docs/testing/helpers.md
1. Balanced some brackets in code example.
=> Balance brackets in code example

.changeset/tidy-trains-shave.md, packages/scoped-elements/package.json
1. add type module field to pkg json
I checked all other packages, this one is the only one missing from the looks of it
=> fix(scoped-elements): add type module to pkg json

.changeset/three-taxis-warn.md, packages/codelabs/src/intermediate/lit-html.md, packages/scoped-elements/src/ScopedElementsMixin.js, packages/scoped-elements/src/types.d.ts
=> fix: add scopedElementsVersion

.changeset/dry-fireants-shop.md, packages/eslint-config/index.js
=> feat: eslint rule

README.md
changed twitter's name to new name 𝕏 in Contact Section of README.md
1. changed twitter's name to new name 𝕏 in Contact Section of README.md
This fixes https://github.com/open-wc/open-wc/issues/2724
=> fix: changed twitter's name to new name 𝕏 in Contact Section of README.md

packages/testing-helpers/package.json, yarn.lock
1. One more dependency I missed 🙈
=> Split one more version of lit-html

.changeset/forgotten-toy-manners.md
=> Forgotten Changeset

package.json, packages/dev-server-hmr/src/hmrPlugin.js, tsconfig.browser-base.json, tsconfig.node-base.json, yarn.lock
=> chore: update ts

docs/docs/development/scoped-elements.md
=> docs: code snippet

docs/docs/development/scoped-elements.md
=> docs: polyfill info

.changeset/curvy-timers-speak.md, packages/testing/package.json, yarn.lock
1. Removed the deprecated and unused @open-wc/chai-dom-equals dependency
=> chore(testing): remove unused dependencies

.changeset/young-badgers-jam.md, packages/eslint-config/index.js
=> fix: add flat config support for eslint plugin import

docs/_data/componentLibraries.js
1. I've added [drab](https://drab.robino.dev) to the component libraries array.
=> Update componentLibraries.js - add drab custom element library

.changeset/curly-zebras-lie.md, package-lock.json, packages/lit-helpers/index.d.ts, packages/lit-helpers/package.json
1. Update dependency to include Lit@3
2. Fix issue in `packages/lit-helpers/index.d.ts` that was causing errors when running lint
=> feat(lit-helpers): Allow lit@3

docs/guides/knowledge/lit-element/rendering.md
=> chore: format file

docs/guides/knowledge/events.md
=> Fixed typo in events.md

docs/_data/componentLibraries.js
1. Added mdui to list of libraries
=> docs: added mdui

docs/_data/componentLibraries.js
1. Added [LDRS](https://github.com/GriffinJohnston/ldrs) to the list of community component libraries.
=> Add LDRS to componentLibraries.js

packages/dedupe-mixin/package.json
=> feat: types and pkg.json

.changeset/slow-mirrors-cry.md, packages/dedupe-mixin/package.json
=> chore: retry release

.github/workflows/verify-node.yml
=> chore: update node version

.changeset/stupid-seals-enjoy.md, packages/eslint-plugin-lit-a11y/lib/utils/hasAccessibleChildren.js
=> fix(eslint-plugin-lit-a11y): crash on comments
